CREATE PROCEDURE SP_GET_DECONTARE_REP (@AREP_NAME VARCHAR(128), @PE_NUME INT = NULL) AS
BEGIN

  -- @PE_NUME = 1 - Ordonate pe nume

  SELECT 
    A.ID_GEST_DOCUM,    
    TOTALDOC,
    (SELECT SUM(SUMA) FROM GEST_DECONTARI WHERE ID_GEST_DOCUM = A.ID_GEST_DOCUM) AS DECONTAT
  INTO #DOCUMENTE
    FROM GEST_DOCUM A 
         JOIN REPARTITORI B ON (A.ID_PREDATOR = B.ID_REPARTITORI)
    WHERE B.NUME LIKE @AREP_NAME AND STARE=1
  
  -- TRECEM IN REZULTAT PE CELE STINSE COMPLET SI CA POZITII
  SELECT
    0 AS TIP_DECONTARE,
    ID_GEST_ITEMSI,
    A.ID_GEST_DOCUM,
    PRET_LIVRARE_TVA AS VALOARE,
    PRET_LIVRARE_TVA AS ACHITAT,
    A.TOTALDOC,
    A.DECONTAT
  INTO #LISTA_ITEMSI
  FROM #DOCUMENTE A
       JOIN GEST_ITEMSI B ON (A.ID_GEST_DOCUM = B.ID_GEST_DOCUM)
  WHERE CONVERT(INT, TOTALDOC/10) = CONVERT(INT, DECONTAT/10)

  DELETE FROM #DOCUMENTE WHERE CONVERT(INT, TOTALDOC/10) = CONVERT(INT, DECONTAT/10)

  /* LE ADAUGAM PE CELE NESTINSE */
  INSERT INTO #LISTA_ITEMSI (TIP_DECONTARE, ID_GEST_ITEMSI, ID_GEST_DOCUM, VALOARE, ACHITAT, TOTALDOC, DECONTAT)
  SELECT
    1,
    ID_GEST_ITEMSI,
    A.ID_GEST_DOCUM,
    PRET_LIVRARE_TVA,
    0 AS ACHITAT,
    A.TOTALDOC,
    A.DECONTAT
  FROM #DOCUMENTE A
       JOIN GEST_ITEMSI B ON (A.ID_GEST_DOCUM = B.ID_GEST_DOCUM)
  WHERE ISNULL(DECONTAT,0) = 0

  DELETE FROM #DOCUMENTE WHERE ISNULL(DECONTAT,0) = 0

  /* VEDEM PE CELE CARE S-AU IMPERECHEAT AUTOMAT */
  INSERT INTO #LISTA_ITEMSI (TIP_DECONTARE, ID_GEST_ITEMSI, ID_GEST_DOCUM, VALOARE, ACHITAT, TOTALDOC, DECONTAT)
  SELECT
    3,
    B.ID_GEST_ITEMSI,
    A.ID_GEST_DOCUM,
    B.PRET_LIVRARE_TVA,
    C.SUMA,
    A.TOTALDOC,
    A.DECONTAT
  FROM #DOCUMENTE A
       JOIN GEST_ITEMSI B ON (A.ID_GEST_DOCUM = B.ID_GEST_DOCUM)
       JOIN GEST_DEFALCARE_DECONTARI C ON (B.ID_GEST_ITEMSI = C.ID_GEST_ITEMSI) 

  DELETE FROM #DOCUMENTE WHERE ID_GEST_DOCUM IN (SELECT ID_GEST_DOCUM FROM GEST_ITEMSI A JOIN GEST_DEFALCARE_DECONTARI B ON (A.ID_GEST_ITEMSI = B.ID_GEST_ITEMSI))

  /* LE ADAUGAM PE CELE PARTIALE */
  INSERT INTO #LISTA_ITEMSI (TIP_DECONTARE, ID_GEST_ITEMSI, ID_GEST_DOCUM, VALOARE, ACHITAT, TOTALDOC, DECONTAT)
  SELECT
    4 AS TIP_DECONTARE,
    ID_GEST_ITEMSI,
    A.ID_GEST_DOCUM,
    PRET_LIVRARE_TVA AS VALOARE,
    0  AS ACHITAT,
    TOTALDOC AS TOTALDOC,
    DECONTAT AS ACHITAT
  FROM #DOCUMENTE A
       JOIN GEST_ITEMSI B ON (A.ID_GEST_DOCUM = B.ID_GEST_DOCUM)
  WHERE CONVERT(INT, TOTALDOC/10) <> CONVERT(INT, DECONTAT/10) AND ISNULL(DECONTAT,0) > 0

  SELECT C.TIPMAT, C.DENMAT, A.*, E.NUME, D.NR_DOCUM, D.DATA_DOCUM, F.COD_DOCUM, H.NRDOC, H.DATA, H.EXPLICATIE, ISNULL(H.INCASARI, H.PLATI) AS PLATIT,
         RTRIM(LTRIM(F.COD_DOCUM))+' '+RTRIM(LTRIM(ISNULL(D.NR_DOCUM,'-')))+' '+CONVERT(VARCHAR(10), D.DATA_DOCUM, 103)+' '+RTRIM(LTRIM(E.NUME)) AS DESC_DOCUM
    FROM #LISTA_ITEMSI A
         JOIN GEST_ITEMSI B ON (A.ID_GEST_ITEMSI = B.ID_GEST_ITEMSI)
         JOIN GEST_GNMCL C ON (B.CODMAT = C.CODMAT)
         JOIN GEST_DOCUM D ON (A.ID_GEST_DOCUM = D.ID_GEST_DOCUM)
         JOIN REPARTITORI E ON (D.ID_PRIMITOR = E.ID_REPARTITORI)
         JOIN GEST_TIP_DOCUM F ON (F.ID_GEST_TIP_DOCUM = D.ID_GEST_TIP_DOCUM)
        -- ATENTIE O SA APARA DE MAI MULTE ORI ID_GEST_ITEMSI
         LEFT JOIN GEST_DECONTARI G ON (G.ID_GEST_DOCUM = D.ID_GEST_DOCUM)
         LEFT JOIN BREGISTRU H ON (G.ID_BREGISTRU = ISNULL(H.NR_LIST, COD))
  ORDER BY 
    CASE WHEN @PE_NUME = 1 THEN C.DENMAT ELSE '' END,
    DATA_DOCUM, NR_DOCUM, B.ID_GEST_DOCUM, B.ID_GEST_ITEMSI
END

