CREATE PROCEDURE SP_GEST_TEST_DECONTARE (@ID_GEST_DECONTARI INT) AS
BEGIN
  DECLARE @PRED_INT INT
  DECLARE @PRIM_INT INT
  DECLARE @ID_PREDATOR INT
  DECLARE @ID_PRIMITOR INT
  DECLARE @ID_GEST_DOCUM INT
  DECLARE @ID_BREGISTRU INT
  DECLARE @CODGEST       INT

  SELECT @ID_GEST_DOCUM = ID_GEST_DOCUM, @ID_BREGISTRU = ID_BREGISTRU FROM GEST_DECONTARI WHERE ID_GEST_DECONTARI = @ID_GEST_DECONTARI

  SELECT @CODGEST = CODGEST FROM BREGISTRU WHERE COD = @ID_BREGISTRU

  SELECT @PRED_INT = B.GESTINT, @PRIM_INT = C.GESTINT, @ID_PREDATOR = ID_PREDATOR, @ID_PRIMITOR = ID_PRIMITOR
    FROM GEST_DOCUM A 
         JOIN REPARTITORI B ON (A.ID_PREDATOR = B.ID_REPARTITORI)
         JOIN REPARTITORI C ON (A.ID_PRIMITOR = C.ID_REPARTITORI)
  WHERE A.ID_GEST_DOCUM = @ID_GEST_DOCUM

--  print @pred_int
--  print @prim_int
--  print @id_predator
--  print @id_primitor
--  print @codgest
--  print @id_gest_docum

/*
  IF @PRED_INT = 0 AND @ID_PREDATOR <> ISNULL(@CODGEST,-1)
    UPDATE BREGISTRU SET CODGEST = @ID_PREDATOR WHERE isnull(nr_list, cod) = @ID_BREGISTRU
  ELSE
    IF @PRIM_INT = 0 AND @ID_PRIMITOR <> ISNULL(@CODGEST,-1)
      UPDATE BREGISTRU SET CODGEST = @ID_PRIMITOR WHERE isnull(nr_list, cod) = @ID_BREGISTRU
*/
END

