CREATE PROCEDURE [dbo].[SP_GEST_VALIDARI_DOCUM] (@ID_UTILIZATORI INT, @GET_DELETED BIT = 0, @IS_NESTED BIT = 0) AS
BEGIN

  DECLARE @ID_FUNCTIUNE INT

  SELECT @ID_FUNCTIUNE = ID_FUNCTIUNI FROM UTILIZATORI WHERE ID_UTILIZATORI = @ID_UTILIZATORI

  SET NOCOUNT ON

  SELECT DISTINCT
    A.ID_GEST_DOCUM,
    NR_DOCUM,
    A.DATA_DOCUM,
    RTRIM(LTRIM(B.COD_DOCUM))+' : '+RTRIM(LTRIM(DEN_DOCUM)) AS DOCUMENT,
    C.NUME AS PREDATOR,
    D.NUME AS PRIMITOR,
    --E.ID_FUNCTIUNE 
    0 AS ID_FUNCTIUNI,
    PRIORITATE,
    DATEADD(DAY, ZILE_GRATIE, A.DATA_DOCUM) AS DATA_EXPIRARE,
    ZILE_GRATIE - DATEDIFF(DAY, GETDATE(), A.DATA_DOCUM) AS ZILE_RAMASE,
    CASE WHEN DATALENGTH(G.DOCUMENT_FIZIC) > 100 THEN 1 ELSE 0 END AS ARE_DOC_FIZIC
  INTO #LISTA_DOCUMENTE
      FROM GEST_DOCUM A
           JOIN GEST_TIP_DOCUM B ON (A.ID_GEST_TIP_DOCUM = B.ID_GEST_TIP_DOCUM)
           JOIN REPARTITORI C ON (A.ID_PREDATOR = C.ID_REPARTITORI)
           JOIN REPARTITORI D ON (A.ID_PRIMITOR = D.ID_REPARTITORI)
           JOIN GEST_TEMPLATE_VALIDARI E ON (E.ID_GEST_DEFA_DOCUM = A.ID_GEST_DEFA_DOCUM)
           JOIN .DBO.FN_GET_TREE_FUNCTII (@ID_FUNCTIUNE) F ON (F.ID_FUNCTIUNI = E.ID_FUNCTIUNE)
           LEFT JOIN GEST_FORMA_FIZICA G on (A.ID_GEST_DOCUM = G.ID_GEST_DOCUM)
           join gest_defa_docum H on (a.id_gest_defa_docum = h.id_gest_defa_docum)
      WHERE 
          A.VALIDAT = 1 AND A.STARE=1 
          and CASE WHEN DATALENGTH(G.DOCUMENT_FIZIC) > 100 THEN 1 ELSE 0 END = 1
           AND (E.TIP_VALIDARE & 2 = 2  -- NUMAI CEI CARE INTRODUC
                 OR E.TIP_VALIDARE = 0)  -- SI CEI CARE TREBUIESC INFORMATI
            AND EXISTS (SELECT 1 FROM GEST_VALIDARI_DOCUM WHERE ID_GEST_DOCUM = A.ID_GEST_DOCUM AND TIP_VALIDARE & 1 = 1) -- NUMAI CELE CARE SE VALIDEAZA
--          and isnull(h.is_printing, 0) = 1

  SET NOCOUNT OFF

  UPDATE #LISTA_DOCUMENTE SET ID_FUNCTIUNI = @ID_FUNCTIUNE

	IF @IS_NESTED = 1
   INSERT INTO #TMP_LIST_DOCS (ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE)
   SELECT ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE FROM #LISTA_DOCUMENTE
  ELSE
   SELECT ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE, ARE_DOC_FIZIC FROM #LISTA_DOCUMENTE
   ORDER BY DATA_DOCUM 

END


