CREATE PROCEDURE SP_GEST_NEED_VALIDARI_DOCUM (@ID_UTILIZATORI INT, @GET_VALIDATE INT = 0, @GET_DELETED BIT = 0, @IS_NESTED BIT = 0) AS
BEGIN

  DECLARE @ID_FUNCTIUNE INT

  IF @GET_VALIDATE IS NULL
    SET @GET_VALIDATE = 0

  SELECT @ID_FUNCTIUNE = ID_FUNCTIUNI FROM UTILIZATORI WHERE ID_UTILIZATORI = @ID_UTILIZATORI

  SET NOCOUNT ON

  SELECT   
    A.ID_GEST_DOCUM,
    NR_DOCUM,
    DATA_DOCUM,
    RTRIM(LTRIM(B.COD_DOCUM))+' : '+RTRIM(LTRIM(DEN_DOCUM)) AS DOCUMENT,
    C.NUME AS PREDATOR,
    D.NUME AS PRIMITOR,
    E.ID_FUNCTIUNE AS ID_FUNCTIUNI,
    PRIORITATE,
    DATEADD(DAY, ZILE_GRATIE, A.DATA_DOCUM) AS DATA_EXPIRARE,
    ZILE_GRATIE - DATEDIFF(DAY, GETDATE(), A.DATA_DOCUM) AS ZILE_RAMASE,
    CASE WHEN DATALENGTH(G.DOCUMENT_FIZIC) > 100 THEN 1 ELSE 0 END AS ARE_DOC_FIZIC
  INTO #LISTA_DOCUMENTE
      FROM GEST_DOCUM A
           JOIN GEST_TIP_DOCUM B ON (A.ID_GEST_TIP_DOCUM = B.ID_GEST_TIP_DOCUM)
           JOIN REPARTITORI C ON (A.ID_PREDATOR = C.ID_REPARTITORI)
           JOIN REPARTITORI D ON (A.ID_PRIMITOR = D.ID_REPARTITORI)
           JOIN GEST_VALIDARI_DOCUM E ON (E.ID_GEST_DOCUM = A.ID_GEST_DOCUM)
           JOIN .DBO.FN_GET_TREE_FUNCTII (@ID_FUNCTIUNE) F ON (F.ID_FUNCTIUNI = E.ID_FUNCTIUNE)
           LEFT JOIN GEST_FORMA_FIZICA G on (A.ID_GEST_DOCUM = G.ID_GEST_DOCUM)
      WHERE (@GET_VALIDATE = 1 OR E.ID_LOGARE_USERS IS NULL)            
            AND A.STARE=1


  SET NOCOUNT OFF

	IF @IS_NESTED = 1
   INSERT INTO #TMP_LIST_DOCS (ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE)
   SELECT ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE FROM #LISTA_DOCUMENTE
  ELSE
   SELECT ID_GEST_DOCUM, NR_DOCUM, DATA_DOCUM, DOCUMENT, PREDATOR, PRIMITOR, ID_FUNCTIUNI, PRIORITATE, DATA_EXPIRARE, ZILE_RAMASE, ARE_DOC_FIZIC FROM #LISTA_DOCUMENTE
   ORDER BY DATA_DOCUM 

END

