create procedure spDecontariImperecheate 
as
begin
  SELECT 
      ID_GEST_DECONTARI, A.ID_GEST_DOCUM, A.ID_BREGISTRU, A.SUMA,
      B.TIPDOC, B.NRDOC, B.DATA, B.EXPLICATIE, D.COD_DOCUM, ISNULL(G.IS_BANCA, 0) AS IS_BANCA,
      C.NR_DOCUM, C.DATA_DOCUM, E.NUME AS PREDATOR, F.NUME AS PRIMITOR, CASE WHEN ISNULL(B.NR_LIST, B.COD) IS NULL THEN 2 ELSE C.STARE END AS STARE
  FROM GEST_DECONTARI A
       LEFT JOIN BREGISTRU B ON (A.ID_BREGISTRU = ISNULL(B.NR_LIST, B.COD))
       LEFT JOIN CASIERIE  G ON (G.COD_CB = B.COD_CB)
       LEFT JOIN GEST_DOCUM C ON (A.ID_GEST_DOCUM = C.ID_GEST_DOCUM)
       LEFT JOIN GEST_TIP_DOCUM D ON (C.ID_GEST_TIP_DOCUM = D.ID_GEST_TIP_DOCUM)
       LEFT JOIN REPARTITORI E ON (E.ID_REPARTITORI = C.ID_PREDATOR)
       LEFT JOIN REPARTITORI F ON (F.ID_REPARTITORI = C.ID_PRIMITOR)
end


