create procedure [dbo].[spGestIntrodValidari] (@idGestDocum int=null, @idDefaDocum int = null)
as
begin
   INSERT INTO GEST_VALIDARI_DOCUM (ID_FUNCTIUNE, ID_GEST_DOCUM, ZILE_GRATIE, PRIORITATE, TIP_VALIDARE)
   SELECT ID_FUNCTIUNE, @idGestDocum AS ID_GEST_DOCUM, ZILE_GRATIE, PRIORITATE, TIP_VALIDARE
   FROM GEST_TEMPLATE_VALIDARI WHERE ID_GEST_DEFA_DOCUM = @idDefaDocum AND TIP_VALIDARE & 1 = 1
end

