CREATE PROCEDURE [dbo].[spGestStocInCache] (@ID_CULGEST_DOCUM INT = NULL, @ID_UTILIZATORI INT, @PREDATOR INT, @DATA_STOC DATETIME, @CONT VARCHAR(50),  @DELETE BIT = 0) AS  
BEGIN  
  SET NOCOUNT ON  

/*
--  sold initial excel, alta baza etc
  IF @DATA_STOC <= '01/01/2008'
  BEGIN
    EXEC C_PIT_2007..SP_GET_STOC_DOCUMENT_IN_CACHE @ID_CULGEST_DOCUM, @ID_UTILIZATORI, @PREDATOR, @DATA_STOC, @CONT, @DELETE

    IF @DELETE = 1 
      DELETE FROM CULGEST_ITEMSI WHERE ID_CULGEST_DOCUM =@ID_CULGEST_DOCUM

    INSERT INTO CULGEST_ITEMSI (
        ID_CULGEST_DOCUM, ID_ANGAJAMENTE_DEFALCARE, DETALII_ANGAJAMENT, ID_UTILIZATORI, 
        COD_FUNCTIONAL, COD_ECONOMIC, CODMAT, ID_GEST_TIP_MATERIAL, ID_GEST_TIP_STOCK, STOCK_BEFORE, CANTITATE, 
        STOCK_AFTER, PRET_UNITAR, PRET_RECEPTIE, COTA_TVA, PRET_RECEPTIE_TVA, PRET_LIVRARE, PRET_LIVRARE_TVA, 
        PRET_LIVRARE_VALUTA, TIPMAT, DENMAT, UM, LOHN, DATA_COD, DATA_EXPIRARE, TVA, PRODUS, ID_GEST_SUMATOR,
        LOT_FABRICATIE, UM_SUPLIMENTARA, CONVERSIE_UM, CANTITATE_SUPLIMENTARA, PRET_RECEPTIE_VALUTA,
        TVA_LIVRARE, TVA_RECEPTIE, VALOARE_LIVRARE, VALOARE_LIVRARE_TVA, VALOARE_RECEPTIE_VALUTA, 
        VALOARE_LIVRARE_VALUTA, VALOARE_RECEPTIE, VALOARE_RECEPTIE_TVA, COD_TARIF_VAMAL, TVA_AMANAT,
        ADAOS, CANTITATE_ESTIMATA, ADAOS_IMPUS, CATEGORIE_GRUPARE, TIP_VALUTA_RECEPTIE, TIP_VALUTA_LIVRARE,
        COTA_ADAOS, COTA_ADAOS_IMPUS
    )  
    select 
        ID_CULGEST_DOCUM, ID_ANGAJAMENTE_DEFALCARE, DETALII_ANGAJAMENT, ID_UTILIZATORI, 
        COD_FUNCTIONAL, COD_ECONOMIC, CODMAT, ID_GEST_TIP_MATERIAL, ID_GEST_TIP_STOCK, STOCK_BEFORE, CANTITATE, 
        STOCK_AFTER, PRET_UNITAR, PRET_RECEPTIE, COTA_TVA, PRET_RECEPTIE_TVA, PRET_LIVRARE, PRET_LIVRARE_TVA, 
        PRET_LIVRARE_VALUTA, TIPMAT, DENMAT, UM, LOHN, DATA_COD, DATA_EXPIRARE, TVA, PRODUS, ID_GEST_SUMATOR,
        LOT_FABRICATIE, UM_SUPLIMENTARA, CONVERSIE_UM, CANTITATE_SUPLIMENTARA, PRET_RECEPTIE_VALUTA,
        TVA_LIVRARE, TVA_RECEPTIE, VALOARE_LIVRARE, VALOARE_LIVRARE_TVA, VALOARE_RECEPTIE_VALUTA, 
        VALOARE_LIVRARE_VALUTA, VALOARE_RECEPTIE, VALOARE_RECEPTIE_TVA, COD_TARIF_VAMAL, TVA_AMANAT,
        ADAOS, CANTITATE_ESTIMATA, ADAOS_IMPUS, CATEGORIE_GRUPARE, TIP_VALUTA_RECEPTIE, TIP_VALUTA_LIVRARE,
        COTA_ADAOS, COTA_ADAOS_IMPUS
    from C_PIT_2007..culgest_itemsi where ID_CULGEST_DOCUM =@ID_CULGEST_DOCUM

    IF @DELETE = 1 
      DELETE FROM C_PIT_2007..CULGEST_ITEMSI WHERE ID_CULGEST_DOCUM =@ID_CULGEST_DOCUM


    RETURN
  END
*/

  IF @DELETE = 1 
    DELETE FROM CULGEST_ITEMSI WHERE ID_CULGEST_DOCUM =@ID_CULGEST_DOCUM


 SELECT 
    CODMAT, 
    max(produs) as produs,
    isnull((select top 1 id_gest_tip_material from gest_tip_material where cont like @CONT),  max(id_gest_tip_material)) as id_gest_tip_material,
    max(pret_unitar) as pret_unitar,
    max(pret_receptie) as pret_receptie,
    max(pret_receptie_tva) as pret_receptie_tva,
    max(id_gest_sumator) as id_gest_sumator, max(DENMAT) as denmat, COD_ECONOMIC, SUM(STOCK) AS STOCK, SUM(STOCKVALORIC) AS STOCKVALORIC,
    CONVERT(INT, NULL) AS ID_ANGAJAMENTE_DEFALCARE,
    CONVERT(VARCHAR(50), NULL) AS COD_FUNCTIONAL,
    CONVERT(INT, NULL) AS ID_GEST_TIP_STOCK
 INTO #STOCK_CONT
 FROM 
      DBO.FNSTOCKCODMAT(@DATA_STOC) 
    WHERE ID_GEST_TIP_STOC = 1 AND GESTINT= 1 AND ID_REPARTITORI = @PREDATOR 
      AND (@CONT = '-1' or dbo.fnGetContDebitItems(null, id_gest_tip_material, cod_economic) = @CONT)
      AND (STOCKVALORIC <> 0 OR  STOCK <> 0)
    GROUP BY 
      CODMAT, COD_ECONOMIC
    HAVING 
      SUM(STOCK) <> 0 OR  SUM(STOCKVALORIC) <> 0 

 UPDATE A SET 
    A.COD_FUNCTIONAL = (SELECT TOP 1 COD_FUNCTIONAL FROM GEST_ITEMSI AA JOIN GEST_DOCUM BB ON (AA.ID_GEST_DOCUM = BB.ID_GEST_DOCUM)
      WHERE AA.CODMAT = A.CODMAT AND BB.ID_PRIMITOR = @PREDATOR AND AA.STARE = 1 AND BB.STARE = 1 ORDER BY DATA_DOCUM -  @DATA_STOC ),
    A.ID_ANGAJAMENTE_DEFALCARE = 
      (SELECT TOP 1 ID_ANGAJAMENTE_DEFALCARE FROM GEST_ITEMSI AA JOIN GEST_DOCUM BB ON (AA.ID_GEST_DOCUM = BB.ID_GEST_DOCUM)
      WHERE AA.CODMAT = A.CODMAT AND BB.ID_PRIMITOR = @PREDATOR AND AA.STARE = 1 AND BB.STARE = 1 ORDER BY DATA_DOCUM -  @DATA_STOC ),
    A.ID_GEST_TIP_STOCK = 
      (SELECT TOP 1 ID_GEST_TIP_STOCK FROM GEST_ITEMSI AA JOIN GEST_DOCUM BB ON (AA.ID_GEST_DOCUM = BB.ID_GEST_DOCUM)
      WHERE AA.CODMAT = A.CODMAT AND BB.ID_PRIMITOR = @PREDATOR AND AA.STARE = 1 AND BB.STARE = 1 ORDER BY DATA_DOCUM -  @DATA_STOC )
  FROM #STOCK_CONT A


  -- PRELUAM SI ITEMSII  
  INSERT INTO CULGEST_ITEMSI (
      ID_CULGEST_DOCUM, ID_ANGAJAMENTE_DEFALCARE, DETALII_ANGAJAMENT, ID_UTILIZATORI, 
      COD_FUNCTIONAL, COD_ECONOMIC, CODMAT, ID_GEST_TIP_MATERIAL, ID_GEST_TIP_STOCK, STOCK_BEFORE, CANTITATE, 
      STOCK_AFTER, PRET_UNITAR, PRET_RECEPTIE, COTA_TVA, PRET_RECEPTIE_TVA, PRET_LIVRARE, PRET_LIVRARE_TVA, 
      PRET_LIVRARE_VALUTA, TIPMAT, DENMAT, UM, LOHN, DATA_COD, DATA_EXPIRARE, TVA, PRODUS, ID_GEST_SUMATOR,
      LOT_FABRICATIE, UM_SUPLIMENTARA, CONVERSIE_UM, CANTITATE_SUPLIMENTARA, PRET_RECEPTIE_VALUTA,
      TVA_LIVRARE, TVA_RECEPTIE, VALOARE_LIVRARE, VALOARE_LIVRARE_TVA, VALOARE_RECEPTIE_VALUTA, 
      VALOARE_LIVRARE_VALUTA, VALOARE_RECEPTIE, VALOARE_RECEPTIE_TVA, COD_TARIF_VAMAL, TVA_AMANAT,
      ADAOS, CANTITATE_ESTIMATA, ADAOS_IMPUS, CATEGORIE_GRUPARE, TIP_VALUTA_RECEPTIE, TIP_VALUTA_LIVRARE,
      COTA_ADAOS, COTA_ADAOS_IMPUS
  )  

    SELECT 
        @ID_CULGEST_DOCUM AS ID_CULGEST_DOCUM, C.ID_ANGAJAMENTE_DEFALCARE, 
        CASE WHEN B.ID_ANGAJAMENTE_DEFALCARE IS NULL THEN 'AG: ' ELSE 'AL: ' END+ISNULL(RTRIM(LTRIM(C.COD_FUNCTIONAL)),'-')+'/'+ISNULL(RTRIM(LTRIM(C.COD_ECONOMIC)),'-'), @ID_UTILIZATORI AS ID_UTILIZATORI, 
        C.COD_FUNCTIONAL, C.COD_ECONOMIC, B.CODMAT, C.ID_GEST_TIP_MATERIAL, C.ID_GEST_TIP_STOCK, 0 AS STOCK_BEFORE, C.STOCK AS CANTITATE, 
        C.STOCK AS STOCK_AFTER, C.PRET_UNITAR, C.PRET_RECEPTIE,case when C.PRET_UNITAR = c.PRET_RECEPTIE_TVA then 0 else B.COTA_TVA end as cota_tva, C.PRET_RECEPTIE_TVA, C.PRET_UNITAR * C.STOCK as PRET_LIVRARE, C.STOCKVALORIC AS PRET_LIVRARE_TVA, 
        NULL AS PRET_LIVRARE_VALUTA, B.TIPMAT, B.DENMAT, B.UM, B.LOHN, B.DATA_COD, B.DATA_EXPIRARE, C.STOCKVALORIC - C.PRET_RECEPTIE_TVA * C.STOCK  as  TVA, 
        C.PRODUS, C.ID_GEST_SUMATOR,
        B.LOT_FABRICATIE, B.UM_SUPLIMENTARA, B.CONVERSIE_UM, NULL AS CANTITATE_SUPLIMENTARA, B.PRET_RECEPTIE_VALUTA,
        C.STOCKVALORIC - C.PRET_RECEPTIE_TVA * C.STOCK AS TVA_LIVRARE, C.STOCKVALORIC - C.PRET_RECEPTIE_TVA * C.STOCK AS TVA_RECEPTIE, C.PRET_UNITAR * C.STOCK AS VALOARE_LIVRARE, C.STOCKVALORIC AS VALOARE_LIVRARE_TVA, 0 AS VALOARE_RECEPTIE_VALUTA, 
        0 AS VALOARE_LIVRARE_VALUTA, C.PRET_UNITAR * C.STOCK AS VALOARE_RECEPTIE, 
        C.STOCKVALORIC AS VALOARE_RECEPTIE_TVA, B.COD_TARIF_VAMAL, B.TVA_AMANAT,
        B.ADAOS, NULL AS CANTITATE_ESTIMATA, B.ADAOS_IMPUS, B.CATEGORIE_GRUPARE, NULL AS TIP_VALUTA_RECEPTIE, NULL AS TIP_VALUTA_LIVRARE,
        B.COTA_ADAOS, B.COTA_ADAOS_IMPUS
    FROM 
       #STOCK_CONT C JOIN GEST_GNMCL B ON (C.CODMAT = B.CODMAT)  


  SET NOCOUNT OFF  

END 







