create view vGEST_DEFA_DOCUM_STOC as 
  SELECT DISTINCT a.ID_GEST_DEFA_DOCUM, c.ID_GEST_TIP_STOC, c.PREDATOR FROM GEST_DEFA_DOCUM A JOIN GEST_TIP_DOCUM B ON (A.ID_GEST_TIP_DOCUM = B.ID_GEST_TIP_DOCUM)
  JOIN GEST_DEFA_STOC_TIP_PRODUSE C ON (C.ID_GEST_defa_DOCUM = a.ID_GEST_defa_DOCUM)


