// GENERAT — nu se editează cu mâna.
// Sursa: foaia `Unitati_masura` din `RO_SAFT_SchemaDefCod_16.02.2026.xlsx` (ANAF).
// Regenerare:
//   uv run --no-project python nou/tools/ModelCheck/scripts/genereaza-unitati-masura.py \
//       anaf/RO_SAFT_SchemaDefCod_16.02.2026.xlsx \
//       nou/Atlas.Conta.BackOffice/Atlas.Conta.BackOffice.Module/BusinessObjects/Comun/UnitatiMasuraUnEce.cs

namespace Atlas.Conta.BackOffice.Module.BusinessObjects;

// Codurile UN/ECE Rec 20 + Rec 21 pe care le cere SAF-T (`UOMBase`/`UOMStandard`),
// exact lista publicată de ANAF. LEGE, ca `JudeteRo` — de aceea stă în cod și nu
// în CSV de seed: `SeedUnitatiMasura` o consumă, dar `UnitatiMasuraRo.Rezolva` o
// citește ÎNAINTE de a atinge baza (conectoarele rezolvă UM-uri libere din 1C).
//
// Denumirea e traducerea românească indicativă publicată de ANAF; unde ea
// lipsește (2 coduri), e denumirea engleză.
public static class UnitatiMasuraUnEce {
    public static readonly IReadOnlyList<(string Cod, string Denumire)> Toate = [
        ("10", "grup"),
        ("11", "articole de îmbrăcăminte"),
        ("13", "rație"),
        ("14", "explozie"),
        ("15", "bară, militar"),
        ("20", "container de 20 de picioare"),
        ("21", "container de 40 de picioare"),
        ("22", "decilitru per gram"),
        ("23", "gram per centimetru cub"),
        ("24", "livră teoretică"),
        ("25", "gram per centimetru cub"),
        ("27", "tonă teoretică"),
        ("28", "kilogram per metru pătrat"),
        ("33", "kilopascal în metru pătrat pe gram"),
        ("34", "kilopascal pe milimetru"),
        ("35", "mililitru pe centimetru pătrat secundă"),
        ("37", "uncie pe metru pătrat"),
        ("38", "uncie pe picior pătrat pe 0,01 inch"),
        ("40", "mililitru pe secundă"),
        ("41", "mililitru pe minut"),
        ("56", "sitas - unitate de măsură pentru suprafață"),
        ("57", "celulă"),
        ("58", "kilogram net"),
        ("59", "parte per milion"),
        ("60", "procente greutate"),
        ("61", "parte pe miliard (SUA)"),
        ("74", "milipascal"),
        ("77", "mili-inci"),
        ("80", "livră per inci pătrat absolut"),
        ("81", "Henry (inductanță)"),
        ("85", "Picior-Livră-Forță"),
        ("87", "livră per picior cub"),
        ("89", "poise (unitate de măsură pentru vâscozitate)"),
        ("91", "vâscozitate cinematică"),
        ("1I", "rată fixă"),
        ("2A", "radian per secundă"),
        ("2B", "radian per secundă la pătrat"),
        ("2C", "raze roentgen"),
        ("2G", "Volți AC"),
        ("2H", "Volți DC"),
        ("2I", "Unitate termică britanică (masă internațională) pe oră"),
        ("2J", "centimetru cub per secundă"),
        ("2K", "picior cub per oră"),
        ("2L", "picior cub per minut"),
        ("2M", "centimetru per secundă"),
        ("2N", "decibel"),
        ("2P", "kilobyte"),
        ("2Q", "kilobecquerel"),
        ("2R", "kilocurie"),
        ("2U", "megagram"),
        ("2X", "metru per minut"),
        ("2Y", "milliroentgen"),
        ("2Z", "milivolt"),
        ("3B", "megajoule"),
        ("3C", "om-lună"),
        ("4C", "centistokes"),
        ("4G", "microlitru"),
        ("4H", "micrometru (micron)"),
        ("4K", "miliamper"),
        ("4L", "megabyte"),
        ("4M", "miligram per oră"),
        ("4N", "megabecquerel"),
        ("4O", "microfarad"),
        ("4P", "newton per metru"),
        ("4Q", "uncie inch"),
        ("4R", "uncie picior"),
        ("4T", "picofarad"),
        ("4U", "livră per oră"),
        ("4W", "tonă (SUA) per oră"),
        ("4X", "kilolitru per oră"),
        ("5A", "baril (SUA) per minut"),
        ("5B", "lot"),
        ("5E", "MMSCF/zi"),
        ("5J", "cai-putere în sistemele hidraulice"),
        ("A10", "amper metru pătrat per joule secundă"),
        ("A11", "angstrom"),
        ("A12", "unitate astronomică"),
        ("A13", "attojoule"),
        ("A14", "hambar"),
        ("A15", "hambar per electronvolt"),
        ("A16", "hambar per electronvolt sterradian"),
        ("A17", "hambar per steradian"),
        ("A18", "becquerel per kilogram"),
        ("A19", "becquerel per metru cub"),
        ("A2", "amperi pe centimetru"),
        ("A20", "Unitate termică britanică (tabel internațional) per secundă de picior la pătrat grad Rankine"),
        ("A21", "Unitate termică britanică (tabel internațional) per livră grad Rankine"),
        ("A22", "Unitate termică britanică (tabel internațional) per gradul secund de picior Rankine"),
        ("A23", "Unitate termică britanică (tabel internațional) per oră grad Rankine de picior pătrat"),
        ("A24", "candela per metru pătrat"),
        ("A26", "metru coulomb"),
        ("A27", "metru coulomb pătrat pe volt"),
        ("A28", "coulomb per centimetru cub"),
        ("A29", "coulomb per metru cub"),
        ("A3", "amperi pe milimetru"),
        ("A30", "coulomb per milimetru cub"),
        ("A31", "coulomb per kilogram secundă"),
        ("A32", "coulomb per mol"),
        ("A33", "coulomb per centimetru pătrat"),
        ("A34", "coulomb per metru pătrat"),
        ("A35", "coulomb per milimetru pătrat"),
        ("A36", "centimetru cub per mol"),
        ("A37", "decimetru cub per mol"),
        ("A38", "metru cub per coulomb"),
        ("A39", "metru cub per kilogram"),
        ("A4", "amperi per centimetru pătrat"),
        ("A40", "metru cub per mol"),
        ("A41", "amperi pe metru pătrat"),
        ("A42", "curie per kilogram"),
        ("A43", "tonaj greu"),
        ("A44", "decalitru"),
        ("A45", "decametru"),
        ("A47", "decitex"),
        ("A48", "gradul Rankine"),
        ("A49", "negator"),
        ("A5", "amper metru pătrat"),
        ("A53", "electronvolt"),
        ("A54", "electronvolt per metru"),
        ("A55", "electronvolt-metru pătrat"),
        ("A56", "electronvolt-metru pătrat pe kilogram"),
        ("A59", "nor (8-part cloud cover)"),
        ("A6", "amperi per metru pătrat kelvin pătrat"),
        ("A68", "exajoule"),
        ("A69", "farad per metru"),
        ("A7", "amperi per milimetru pătrat"),
        ("A70", "femtojoule"),
        ("A71", "femtometru"),
        ("A73", "picior per secundă pătrat"),
        ("A74", "picior livră-forță pe secundă"),
        ("A75", "tonă de marfă"),
        ("A76", "gal"),
        ("A8", "amper secundă"),
        ("A84", "gigacoulomb pe metru cub"),
        ("A85", "gigaelectronvolt"),
        ("A86", "gigahertz"),
        ("A87", "gigaohm"),
        ("A88", "gigaohmmetru"),
        ("A89", "gigapascal"),
        ("A9", "coeficient/rată"),
        ("A90", "gigawatt"),
        ("A91", "gon"),
        ("A93", "gram per metru cub"),
        ("A94", "gram per mol"),
        ("A95", "gray (doza de radiații ionizante)"),
        ("A96", "gray per secundă"),
        ("A97", "hectopascal"),
        ("A98", "henry per metru"),
        ("A99", "bit"),
        ("AA", "hectopascal"),
        ("AB", "ambalaj vrac"),
        ("ACR", "acru"),
        ("ACT", "activitate"),
        ("AD", "octet"),
        ("AE", "amper per metru"),
        ("AH", "minut suplimentar"),
        ("AI", "minut mediu per apel"),
        ("AK", "fathom"),
        ("AL", "linie de acces"),
        ("AMH", "amperi oră"),
        ("AMP", "amper"),
        ("ANN", "an"),
        ("APZ", "uncie troy sau uncie de farmacie"),
        ("AQ", "unitate factor anti-hemofil (AHF)."),
        ("AS", "sortiment"),
        ("ASM", "tărie alcoolică în masă"),
        ("ASU", "tărie alcoolică în volum"),
        ("ATM", "atmosferă standard"),
        ("AWG", "sistem de măsurare AWG"),
        ("AY", "ansamblu"),
        ("AZ", "Unitate termică britanică (masă internațională) per livră"),
        ("B1", "baril (SUA) pe zi"),
        ("B10", "bit per secundă"),
        ("B11", "joule per kilogram kelvin"),
        ("B12", "joule per metru"),
        ("B13", "joule per metru pătrat"),
        ("B14", "joule per metru la puterea patru"),
        ("B15", "joule per mol"),
        ("B16", "joule per mol kelvin"),
        ("B17", "credit"),
        ("B18", "joule secundă"),
        ("B19", "cifră"),
        ("B20", "joule metru pătrat pe kilogram"),
        ("B21", "kelvin per watt"),
        ("B22", "kiloamperi"),
        ("B23", "kiloamperi per metru pătrat"),
        ("B24", "kiloamperi per metru"),
        ("B25", "kilobecquerel per kilogram"),
        ("B26", "kilocoulomb"),
        ("B27", "kilocoulomb per metru cub"),
        ("B28", "kilocoulomb pe metru pătrat"),
        ("B29", "kiloelectronvolt"),
        ("B3", "batting livră"),
        ("B30", "gibit"),
        ("B31", "kilogram metru pe secundă"),
        ("B32", "kilogram metru pătrat"),
        ("B33", "kilogram metru pătrat per secundă"),
        ("B34", "kilogram per decimetru cub"),
        ("B35", "kilogram per litru"),
        ("B4", "unitate de capacitate, imperial"),
        ("B41", "kilojoul per kelvin"),
        ("B42", "kilojoule per kilogram"),
        ("B43", "kilojoule per kilogram kelvin"),
        ("B44", "kilojoul per mol"),
        ("B45", "kilomol"),
        ("B46", "kilomol per metru cub"),
        ("B47", "kilonewton"),
        ("B48", "kilonewton metru"),
        ("B49", "kiloohm"),
        ("B50", "kiloohmmetru"),
        ("B52", "kilosecundă"),
        ("B53", "kilosiemens"),
        ("B54", "kilosiemens per metru"),
        ("B55", "kilovolt per metru"),
        ("B56", "kiloweber per metru"),
        ("B57", "an lumină"),
        ("B58", "litru per mol"),
        ("B59", "oră lumen"),
        ("B60", "lumen per metru pătrat"),
        ("B61", "lumen per watt"),
        ("B62", "lumen secundă"),
        ("B63", "oră lux"),
        ("B64", "secundă lux"),
        ("B66", "megaamperi per metru pătrat"),
        ("B67", "megabecquerel per kilogram"),
        ("B68", "gigabit"),
        ("B69", "megacoulomb per metru cub"),
        ("B7", "ciclu"),
        ("B70", "megacoulomb per metru pătrat"),
        ("B71", "megaelectronvolt"),
        ("B72", "megagram per metru cub"),
        ("B73", "meganewton"),
        ("B74", "metru meganewton"),
        ("B75", "megaohm"),
        ("B76", "megaohmmetru"),
        ("B77", "megaohmmetru"),
        ("B78", "megavolt"),
        ("B79", "megavolt per metru"),
        ("B8", "joule pe metru cub"),
        ("B80", "gigabit per secundă"),
        ("B81", "metru reciproc pătrat secundă reciprocă"),
        ("B82", "inch per picior liniar"),
        ("B83", "metru la puterea a patra"),
        ("B84", "microamper"),
        ("B85", "microbar"),
        ("B86", "microcoulomb"),
        ("B87", "microcoulomb per metru cub"),
        ("B88", "microcoulomb per metru pătrat"),
        ("B89", "microfarad pe metru"),
        ("B90", "microhenry"),
        ("B91", "microhenry per metru"),
        ("B92", "micronewton"),
        ("B93", "micronewton metru"),
        ("B94", "microohm"),
        ("B95", "microohm metru"),
        ("B96", "micropascal"),
        ("B97", "microradian"),
        ("B98", "microsecundă"),
        ("B99", "microsiemens"),
        ("BAR", "bar [unitate de presiune]"),
        ("BB", "cutie de bază"),
        ("BFT", "picior de bord"),
        ("BHP", "cai-putere"),
        ("BIL", "miliarde (EUR)"),
        ("BLD", "dry barrel (US)"),
        ("BLL", "baril (SUA)"),
        ("BP", "hundred board foot (măsură standard pentru materii lemnoase)"),
        ("BPM", "bătăi per minut"),
        ("BQL", "becquerel"),
        ("BTU", "Unitate termică britanică (tabel internațional)"),
        ("BUA", "bushel (SUA)"),
        ("BUI", "bushel (UK)"),
        ("C0", "call"),
        ("C10", "milifarad"),
        ("C11", "milligal"),
        ("C12", "miligram per metru"),
        ("C13", "miligray"),
        ("C14", "millhenry"),
        ("C15", "milijoule"),
        ("C16", "milimetru per secundă"),
        ("C17", "milimetru pătrat per secundă"),
        ("C18", "milimol"),
        ("C19", "mol per kilogram"),
        ("C20", "milinewton"),
        ("C21", "kibibit"),
        ("C22", "milinewton pe metru"),
        ("C23", "miliohm metru"),
        ("C24", "milipascal secundă"),
        ("C25", "miliradian"),
        ("C26", "milisecundă"),
        ("C27", "millisiemens"),
        ("C28", "milisievert"),
        ("C29", "millitesla"),
        ("C3", "microvolt per metru"),
        ("C30", "milivolt per metru"),
        ("C31", "milliwatt"),
        ("C32", "miliwatt per metru pătrat"),
        ("C33", "milliweber"),
        ("C34", "mol"),
        ("C35", "mol per decimetru cub"),
        ("C36", "mol per metru cub"),
        ("C37", "kilobit"),
        ("C38", "mol per litru"),
        ("C39", "nanoamperi"),
        ("C40", "nanocoulomb"),
        ("C41", "nanofarad"),
        ("C42", "nanofarad per metru"),
        ("C43", "nanohenry"),
        ("C44", "nanohenry per metru"),
        ("C45", "nanometru"),
        ("C46", "nanoohm metru"),
        ("C47", "nanosecundă"),
        ("C48", "nanotesla"),
        ("C49", "nanowatt"),
        ("C50", "neper"),
        ("C51", "neper per secundă"),
        ("C52", "picometru"),
        ("C53", "newton metru secundă"),
        ("C54", "newton metru pătrat pe kilogram pătrat"),
        ("C55", "newton per metru pătrat"),
        ("C56", "newton per milimetru pătrat"),
        ("C57", "newton secundă"),
        ("C58", "newton secundă per metru"),
        ("C59", "octavă"),
        ("C60", "ohm centimetru"),
        ("C61", "ohm-metru"),
        ("C62", "one"),
        ("C63", "parsec"),
        ("C64", "pascal per kelvin"),
        ("C65", "pascal secundă"),
        ("C66", "pascal secundă per metru cub"),
        ("C67", "pascal secundă per metru"),
        ("C68", "petajoule"),
        ("C69", "fon"),
        ("C7", "centipoise"),
        ("C70", "picoamperi"),
        ("C71", "picocoulomb"),
        ("C72", "picofarad per metru"),
        ("C73", "picohenry"),
        ("C74", "kilobit per secundă"),
        ("C75", "picowatt"),
        ("C76", "picowatt pe metru pătrat"),
        ("C78", "livră-forță"),
        ("C79", "kilovolt amperi oră"),
        ("C8", "millicoulomb per kilogram"),
        ("C80", "rad"),
        ("C81", "radian"),
        ("C82", "radian metru pătrat per mol"),
        ("C83", "radian metru pătrat per kilogram"),
        ("C84", "radian per metru"),
        ("C85", "angstrom reciproc"),
        ("C86", "metru cub reciproc"),
        ("C87", "metru cub reciproc per secundă"),
        ("C88", "electronvolt reciproc per metru cub"),
        ("C89", "henry reciproc"),
        ("C9", "grup bobină"),
        ("C90", "Joule reciproc per metru cub"),
        ("C91", "kelvin reciproc sau kelvin la puterea minus unu"),
        ("C92", "metru reciproc"),
        ("C93", "metru pătrat reciproc"),
        ("C94", "minut reciproc"),
        ("C95", "mol reciproc"),
        ("C96", "pascal sau pascal reciproc la puterea minus unu"),
        ("C97", "secundă reciprocă"),
        ("C99", "secundă reciprocă pe metru pătrat"),
        ("CCT", "capacitatea de transport în tone metrice"),
        ("CDL", "candela"),
        ("CEL", "grade Celsius"),
        ("CEN", "sută"),
        ("CG", "card"),
        ("CGM", "centigram"),
        ("CKG", "coulomb per kilogram"),
        ("CLF", "hundred leave"),
        ("CLT", "centilitru"),
        ("CMK", "centimetru pătrat"),
        ("CMQ", "centimetru cub"),
        ("CMT", "centimetru"),
        ("CNP", "o sută unități (hundred pack)"),
        ("CNT", "cental  (Marea Britanie) (unitate centrală)"),
        ("COU", "coulomb"),
        ("CTG", "gram de continut"),
        ("CTM", "carate metrice"),
        ("CTN", "conținut tonă (metric)"),
        ("CUR", "curie"),
        ("CWA", "unitate atomică de masă (cwt) /"),
        ("CWI", "chintal (Marea Britanie)"),
        ("D03", "kilowați oră per oră"),
        ("D04", "lot [unitate de greutate]"),
        ("D1", "secundă reciprocă pe steradian"),
        ("D10", "siemens per metru"),
        ("D11", "mebibit"),
        ("D12", "siemens metru pătrat pe mol"),
        ("D13", "sievert"),
        ("D15", "sone (unitate zgomot)"),
        ("D16", "centimetru pătrat per erg"),
        ("D17", "centimetru pătrat per erg steradian"),
        ("D18", "metru kelvin"),
        ("D19", "metru pătrat kelvin per watt"),
        ("D2", "secundă reciprocă per metru steradian pătrat"),
        ("D20", "metru pătrat per joule"),
        ("D21", "metru pătrat per kilogram"),
        ("D22", "metru pătrat per mol"),
        ("D23", "pen gram (proteine)"),
        ("D24", "metru pătrat per steradian"),
        ("D25", "metru pătrat per joule steradian"),
        ("D26", "metru pătrat per volt secundă"),
        ("D27", "steradian"),
        ("D29", "teraherți"),
        ("D30", "terajoule"),
        ("D31", "terawatt"),
        ("D32", "terawatt oră"),
        ("D33", "tesla"),
        ("D34", "tex"),
        ("D36", "megabit"),
        ("D41", "tonă per metru cub"),
        ("D42", "an tropical"),
        ("D43", "unitate de masă atomică unificată"),
        ("D44", "var"),
        ("D45", "volt pătrat per kelvin pătrat"),
        ("D46", "volt - amper"),
        ("D47", "volt per centimetru"),
        ("D48", "volt per kelvin"),
        ("D49", "milivolt per kelvin"),
        ("D5", "kilogram per centimetru pătrat"),
        ("D50", "volt per metru"),
        ("D51", "volt per milimetru"),
        ("D52", "watt per kelvin"),
        ("D53", "watt pe metru kelvin"),
        ("D54", "watt pe metru pătrat"),
        ("D55", "watt per metru pătrat kelvin"),
        ("D56", "watt per metru pătrat kelvin la a patra putere"),
        ("D57", "watt per steradian"),
        ("D58", "watt per metru pătrat steradian"),
        ("D59", "weber per metru"),
        ("D6", "roentgen per secundă"),
        ("D60", "weber per milimetru"),
        ("D61", "minut [unitate de unghi]"),
        ("D62", "secundă [unitate de unghi]"),
        ("D63", "cantitate"),
        ("D65", "rundă"),
        ("D68", "număr de cuvinte"),
        ("D69", "inch la a patra putere"),
        ("D73", "joule metru pătrat"),
        ("D74", "kilogram per mol"),
        ("D77", "megacoulomb"),
        ("D78", "megajoule per second"),
        ("D80", "microwat"),
        ("D81", "microtesla"),
        ("D82", "microvolt"),
        ("D83", "milinewton metru"),
        ("D85", "microwatt per metru pătrat"),
        ("D86", "millicoulomb"),
        ("D87", "milimol per kilogram"),
        ("D88", "milicoulomb per metru cub"),
        ("D89", "milicoulomb per metru pătrat"),
        ("D91", "rem"),
        ("D93", "secundă per metru cub"),
        ("D94", "secundă per metru cub radian"),
        ("D95", "joule per gram"),
        ("DAA", "decare"),
        ("DAD", "zece zile"),
        ("DAY", "zi"),
        ("DB", "livră mediu uscat"),
        ("DD", "grad [unitate de unghi]"),
        ("DEC", "deceniu"),
        ("DG", "decigram"),
        ("DJ", "decagram"),
        ("DLT", "decilitru"),
        ("DMA", "decametru cub"),
        ("DMK", "decimetru pătrat"),
        ("DMO", "kilolitru standard"),
        ("DMQ", "decimetru cub"),
        ("DMT", "decimetru"),
        ("DN", "decinewton metru"),
        ("DPC", "doisprezece buc."),
        ("DPR", "pereche de doisprezece"),
        ("DPT", "tonaj de deplasare"),
        ("DRA", "dram (SUA)"),
        ("DRI", "dram (Marea Britanie)"),
        ("DRL", "doisprezece roll."),
        ("DT", "tonă mediu uscat"),
        ("DTN", "decitonă"),
        ("DWT", "pennyweight"),
        ("DZN", "doisprezece"),
        ("DZP", "pachet doisprezece"),
        ("E01", "newton pe centimetru pătrat"),
        ("E07", "megawați oră per oră"),
        ("E08", "megawatt pe hertz"),
        ("E09", "miliamperi oră"),
        ("E10", "zi grade"),
        ("E12", "mille"),
        ("E14", "kilocalorie (tabel internațional)"),
        ("E15", "kilocalorii (termochimice) per oră"),
        ("E16", "milioane Btu(IT) pe oră"),
        ("E17", "picior cub pe secundă"),
        ("E18", "tonă pe oră"),
        ("E19", "ping"),
        ("E20", "megabit per secundă"),
        ("E21", "cote"),
        ("E22", "TEU"),
        ("E23", "anvelopă"),
        ("E25", "unitate activă"),
        ("E27", "doză"),
        ("E28", "tonă mediu uscat la aer"),
        ("E30", "toron"),
        ("E31", "metru pătrat per litru"),
        ("E32", "litru per oră"),
        ("E33", "picior la mie"),
        ("E34", "gigabyte"),
        ("E35", "terabyte"),
        ("E36", "petabyte"),
        ("E37", "pixel"),
        ("E38", "megapixel"),
        ("E39", "puncte per inci"),
        ("E4", "kilogramul brut"),
        ("E40", "parte la suta de mii"),
        ("E41", "kilogram-forță per milimetru pătrat"),
        ("E42", "kilogram-forță per centimetru pătrat"),
        ("E43", "joule pe centimetru pătrat"),
        ("E44", "kilogram-forță metru pe centimetru pătrat"),
        ("E45", "miliohmi"),
        ("E46", "kilowatt oră per metru cub"),
        ("E47", "kilowatt-oră per kelvin"),
        ("E48", "unitate de service"),
        ("E49", "zi lucrătoare"),
        ("E50", "unitate de contabilitate"),
        ("E51", "job"),
        ("E52", "rata curentă"),
        ("E53", "test"),
        ("E54", "călătorie"),
        ("E55", "utilizare"),
        ("E56", "godeu"),
        ("E57", "zonă"),
        ("E58", "exabit pe secundă"),
        ("E59", "exbibyte"),
        ("E60", "pebibyte"),
        ("E61", "tebibyte"),
        ("E62", "gibibyte"),
        ("E63", "mebibyte"),
        ("E64", "kibibyte"),
        ("E65", "exbibit pe metru"),
        ("E66", "exbibit pe metru pătrat"),
        ("E67", "exbibit pe metru cub"),
        ("E68", "gigabyte pe secundă"),
        ("E69", "gibibit pe metru"),
        ("E70", "gibibit pe metru pătrat"),
        ("E71", "gibibit pe metru cub"),
        ("E72", "kibibit pe metru"),
        ("E73", "kibibit pe metru pătrat"),
        ("E74", "kibibit pe metru cub"),
        ("E75", "mebibit pe metru"),
        ("E76", "mebibit pe metru pătrat"),
        ("E77", "mebibit pe metru cub"),
        ("E78", "petabit"),
        ("E79", "petabit pe secundă"),
        ("E80", "pebibit pe metru"),
        ("E81", "pebibit pe metru pătrat"),
        ("E82", "pebibit pe metru cub"),
        ("E83", "terabit"),
        ("E84", "terabit pe secundă"),
        ("E85", "tebibit pe metru"),
        ("E86", "tebibit pe metru cub"),
        ("E87", "tebibit pe metru pătrat"),
        ("E88", "bit pe metru"),
        ("E89", "bit pe metru pătrat"),
        ("E90", "centimetru reciproc"),
        ("E91", "zi reciprocă"),
        ("E92", "decimetru cub pe oră"),
        ("E93", "kilogram pe oră"),
        ("E94", "kilomol pe secundă"),
        ("E95", "mol pe secundă"),
        ("E96", "grad pe secundă"),
        ("E97", "milimetru pe grad Celcius metru"),
        ("E98", "grade Celsius pe kelvin"),
        ("E99", "hectopascal pe bar"),
        ("EA", "fiecare"),
        ("EB", "cutie de poștă electronică"),
        ("EQ", "galon echivalent"),
        ("F01", "bit pe metru cub"),
        ("F02", "kelvin pe kelvin"),
        ("F03", "kilopascal pe bar"),
        ("F04", "milibar pe bar"),
        ("F05", "megapascal pe bar"),
        ("F06", "poise pe bar"),
        ("F07", "pascal pe bar"),
        ("F08", "miliamperi pe inch"),
        ("F10", "kelvin pe oră"),
        ("F11", "kelvin pe minut"),
        ("F12", "kelvin pe secundă"),
        ("F13", "slug (unitate tehnică)"),
        ("F14", "gram pe kelvin"),
        ("F15", "kilogram pe kelvin"),
        ("F16", "miligram pe kelvin"),
        ("F17", "livră-forță pe picior"),
        ("F18", "kilogram centimetru pătrat"),
        ("F19", "kilogram milimetru pătrat"),
        ("F20", "livră per inch pătrat"),
        ("F21", "livră-forță inch"),
        ("F22", "livră-forță picior pe amper"),
        ("F23", "gram per decimetru cub"),
        ("F24", "kilogram pe kilomol"),
        ("F25", "gram pe hertz"),
        ("F26", "gram pe zi"),
        ("F27", "gram pe oră"),
        ("F28", "gram pe minut"),
        ("F29", "gram pe secundă"),
        ("F30", "kilogram pe zi"),
        ("F31", "kilogram pe minut"),
        ("F32", "miligram pe zi"),
        ("F33", "miligram pe minut"),
        ("F34", "miligram pe secundă"),
        ("F35", "gram pe zi kelvin"),
        ("F36", "gram pe oră kelvin"),
        ("F37", "gram pe minut kelvin"),
        ("F38", "gram pe secundă kelvin"),
        ("F39", "kilogram pe zi kelvin"),
        ("F40", "kilogram pe oră kelvin"),
        ("F41", "kilogram pe minut kelvin"),
        ("F42", "kilogram pe secundă kelvin"),
        ("F43", "miligram pe zi kelvin"),
        ("F44", "miligram pe oră kelvin"),
        ("F45", "miligram pe minut kelvin"),
        ("F46", "miligram pe secundă kelvin"),
        ("F47", "newton pe milimetru"),
        ("F48", "livră-forță pe inch"),
        ("F49", "rod [unitate de distanță]"),
        ("F50", "micrometru pe kelvin"),
        ("F51", "centimetru pe kelvin"),
        ("F52", "metru pe kelvin"),
        ("F53", "milimetru pe kelvin"),
        ("F54", "miliohmi pe metru"),
        ("F55", "ohm pe milă (mila statutară)"),
        ("F56", "ohm pe kilometru"),
        ("F57", "miliamperi pe livră-forță pe inch pătrat"),
        ("F58", "bar reciproc"),
        ("F59", "miliamperi pe bar"),
        ("F60", "grade Celsius pe bar"),
        ("F61", "kelvin pe bar"),
        ("F62", "gram pe bar zi"),
        ("F63", "gram pe bar oră"),
        ("F64", "gram pe bar minut"),
        ("F65", "gram pe bar secundă"),
        ("F66", "kilogram pe bar zi"),
        ("F67", "kilogram pe bar oră"),
        ("F68", "kilogram pe bar minut"),
        ("F69", "kilogram pe bar secundă"),
        ("F70", "miligram pe bar zi"),
        ("F71", "miligram pe bar oră"),
        ("F72", "miligram pe bar minut"),
        ("F73", "miligram pe bar secundă"),
        ("F74", "gram pe bar"),
        ("F75", "miligram pe bar"),
        ("F76", "miliamperi pe milimetru"),
        ("F77", "pascal secundă pe kelvin"),
        ("F78", "inch de apă"),
        ("F79", "inch de mercur"),
        ("F80", "cai-putere apă"),
        ("F81", "bar pe kelvin"),
        ("F82", "hectopascal pe kelvin"),
        ("F83", "kilopascal pe kelvin"),
        ("F84", "milibar pe kelvin"),
        ("F85", "megapascal pe kelvin"),
        ("F86", "poise pe kelvin"),
        ("F87", "volt pe litru minut"),
        ("F88", "centimetru newton"),
        ("F89", "newton metru pe grad"),
        ("F90", "newton metru pe amper"),
        ("F91", "bar litru pe secundă"),
        ("F92", "bar metru cub pe secundă"),
        ("F93", "hectopascal litru pe secundă"),
        ("F94", "hectopascal metru cub pe secundă"),
        ("F95", "milibar litru pe secundă"),
        ("F96", "milibari metru cub pe secundă"),
        ("F97", "megapascal litru pe secundă"),
        ("F98", "megapascal metru cub pe secundă"),
        ("F99", "pascal litru pe secundă"),
        ("FAH", "grad Fahrenheit"),
        ("FAR", "farad"),
        ("FBM", "contor de fibre"),
        ("FC", "mii de picioare cubi"),
        ("FF", "suta de metri cubi"),
        ("FH", "micromol"),
        ("FIT", "rata de defecțiune"),
        ("FL", "tonă fulgi"),
        ("FOT", "picior"),
        ("FP", "livră pe picior pătrat"),
        ("FR", "picior pe minut"),
        ("FS", "picior pe secundă"),
        ("FTK", "metru pătrat"),
        ("FTQ", "metru cub"),
        ("G01", "pascal metru cub pe secundă"),
        ("G04", "centimetru pe bar"),
        ("G05", "metru pe bar"),
        ("G06", "milimetru pe bar"),
        ("G08", "inch pătrat pe secundă"),
        ("G09", "metru pătrat pe secundă kelvin"),
        ("G10", "stokes pe kelvin"),
        ("G11", "gram pe bar centimetru cub"),
        ("G12", "gram pe bar decimetru cub"),
        ("G13", "gram pe bar litru"),
        ("G14", "gram pe bar metru cub"),
        ("G15", "gram pe bar mililitru"),
        ("G16", "kilogram pe bar centimetru cub"),
        ("G17", "kilogram pe bar litru"),
        ("G18", "kilogram pe bar metru cub"),
        ("G19", "newton metru pe kilogram"),
        ("G2", "galon american pe minut"),
        ("G20", "livră-forță picior pe kilogram"),
        ("G21", "cupă [unitate de volum]"),
        ("G23", "peck (unitate de capacitate)"),
        ("G24", "lingură (SUA)"),
        ("G25", "linguriță (SUA)"),
        ("G26", "ster"),
        ("G27", "centimetru cub pe kelvin"),
        ("G28", "litru pe kelvin"),
        ("G29", "metru cub pe kelvin"),
        ("G3", "galon imperial pe minut"),
        ("G30", "mililitru pe kelvin"),
        ("G31", "kilogram pe centimetru cub"),
        ("G32", "uncie (avoirdupois) pe yard cub"),
        ("G33", "gram pe centimetru cub kelvin"),
        ("G34", "gram pe decimetru cub kelvin"),
        ("G35", "gram pe litru kelvin"),
        ("G36", "gram pe metru cub kelvin"),
        ("G37", "gram pe mililitru kelvin"),
        ("G38", "kilogram pe centimetru cub kelvin"),
        ("G39", "kilogram pe litru kelvin"),
        ("G40", "kilogram pe metru cub kelvin"),
        ("G41", "metru pătrat pe bar secundă"),
        ("G42", "microsiemens pe centimetru"),
        ("G43", "microsiemens pe metru"),
        ("G44", "nanosiemens pe centimetru"),
        ("G45", "nanosiemens pe metru"),
        ("G46", "stokes pe bar"),
        ("G47", "centimetru cub pe zi"),
        ("G48", "centimetru cub pe oră"),
        ("G49", "centimetru cub pe minut"),
        ("G50", "galon (SUA) pe oră"),
        ("G51", "litru pe secundă"),
        ("G52", "cubic metre per day"),
        ("G53", "metru cub pe minut"),
        ("G54", "mililitru pe zi"),
        ("G55", "mililitru pe oră"),
        ("G56", "inch cubi pe oră"),
        ("G57", "inch cubi pe minut"),
        ("G58", "inch cubi pe secundă"),
        ("G59", "miliamperi pe litru minut"),
        ("G60", "volt pe bar"),
        ("G61", "centimetru cub pe zi kelvin"),
        ("G62", "centimetru cub pe oră kelvin"),
        ("G63", "centimetru cub pe minut kelvin"),
        ("G64", "centimetru cub pe secundă kelvin"),
        ("G65", "litru pe zi kelvin"),
        ("G66", "litru pe oră kelvin"),
        ("G67", "litru pe minut kelvin"),
        ("G68", "litru pe secundă kelvin"),
        ("G69", "metru cub pe zi kelvin"),
        ("G70", "metru cub pe oră kelvin"),
        ("G71", "metru cub pe minut kelvin"),
        ("G72", "metru cub pe secundă kelvin"),
        ("G73", "mililitru pe zi kelvin"),
        ("G74", "mililitru pe oră kelvin"),
        ("G75", "mililitru pe minut kelvin"),
        ("G76", "mililitru pe secundă kelvin"),
        ("G77", "milimetru la a patra putere"),
        ("G78", "centimetru cub pe zi bar"),
        ("G79", "centimetru cub pe oră bar"),
        ("G80", "centimetru cub pe minut bar"),
        ("G81", "centimetru cub pe secundă bar"),
        ("G82", "litru pe zi bar"),
        ("G83", "litru pe oră bar"),
        ("G84", "litru pe minut bar"),
        ("G85", "litru pe secundă bar"),
        ("G86", "metru cub pe zi bar"),
        ("G87", "metru cub pe oră bar"),
        ("G88", "metru cub pe minut bar"),
        ("G89", "metru cub pe secundă bar"),
        ("G90", "mililitru pe zi bar"),
        ("G91", "mililitru pe oră bar"),
        ("G92", "mililitru pe minut bar"),
        ("G93", "mililitru pe secundă bar"),
        ("G94", "centimetru cub pe secundă bar"),
        ("G95", "litru pe bar"),
        ("G96", "metru cub pe bar"),
        ("G97", "mililitru pe bar"),
        ("G98", "microhenry per kiloohm"),
        ("G99", "microhenry per ohm"),
        ("GB", "galon (SUA) pe zi"),
        ("GBQ", "gigabecquerel"),
        ("GDW", "gram, greutate uscată"),
        ("GE", "liră pe galon (SUA)"),
        ("GF", "gram pe metru (gram pe 100 de centimetri)"),
        ("GFI", "gram de izotop fisionabil"),
        ("GGR", "great gross (duzină brută)"),
        ("GIA", "gill (unitate de timp)"),
        ("GIC", "gram, inclusiv container"),
        ("GII", "gill (Marea Britanie)"),
        ("GIP", "gram, inclusiv ambalajul interior"),
        ("GJ", "gram pe mililitru"),
        ("GL", "gram pe litru"),
        ("GLD", "galon material uscat (SUA)"),
        ("GLI", "galon (Marea Britanie)"),
        ("GLL", "galon (SUA)"),
        ("GM", "gram pe metru pătrat"),
        ("GO", "miligram pe metru pătrat"),
        ("GP", "miligram pe metru cub"),
        ("GQ", "microgram pe metru cub"),
        ("GRM", "gram"),
        ("GRN", "dram"),
        ("GRO", "total"),
        ("GV", "gigajoule"),
        ("GWH", "gigawatt oră"),
        ("H03", "Henry pe kiloohm"),
        ("H04", "Henry pe ohm"),
        ("H05", "milihenry pe kiloohm"),
        ("H06", "milihenry per ohm"),
        ("H07", "pascal secundă pe bar"),
        ("H08", "microbecquerel"),
        ("H09", "an reciproc"),
        ("H10", "oră reciprocă"),
        ("H11", "lună reciprocă"),
        ("H12", "grade Celsius pe oră"),
        ("H13", "grade Celsius pe minut"),
        ("H14", "grade Celsius pe secundă"),
        ("H15", "centimetru pătrat pe gram"),
        ("H16", "decametru pătrat"),
        ("H18", "hectometru pătrat"),
        ("H19", "hectometru cub"),
        ("H20", "kilometru cub"),
        ("H21", "gol"),
        ("H22", "volt inch pătrat pe livră-forță"),
        ("H23", "volt pe inch"),
        ("H24", "volt pe microsecundă"),
        ("H25", "procente pe kelvin"),
        ("H26", "ohm pe metru"),
        ("H27", "grad pe metru"),
        ("H28", "microfarad pe kilometru"),
        ("H29", "microgram pe litru"),
        ("H30", "micrometru pătrat (micron pătrat)"),
        ("H31", "amperi pe kilogram"),
        ("H32", "amper pătrat secundă"),
        ("H33", "farad pe kilometru"),
        ("H34", "contorul de hertzi"),
        ("H35", "metru kelvin pe watt"),
        ("H36", "megaohm pe kilometru"),
        ("H37", "megaohm pe metru"),
        ("H38", "megaamperi"),
        ("H39", "kilometru megahertz"),
        ("H40", "newton pe amper"),
        ("H41", "newton metru watt la putere minus 0,5"),
        ("H42", "pascal pe metru"),
        ("H43", "siemens pe centimetru"),
        ("H44", "teraohm"),
        ("H45", "volt secundă pe metru"),
        ("H46", "volți pe secundă"),
        ("H47", "watt pe metru cub"),
        ("H48", "attofarad"),
        ("H49", "centimetru pe oră"),
        ("H50", "centimetru cub reciproc"),
        ("H51", "decibel pe kilometru"),
        ("H52", "decibel pe metru"),
        ("H53", "kilogram pe bar"),
        ("H54", "kilogram pe decimetru cub kelvin"),
        ("H55", "kilogram pe bar de decimetru cub"),
        ("H56", "kilogram pe metru pătrat secundă"),
        ("H57", "inch pe doi pi radiant"),
        ("H58", "metru pe volt secundă"),
        ("H59", "metru pătrat pe newton"),
        ("H60", "metru cub pe metru cub"),
        ("H61", "milisiemens pe centimetru"),
        ("H62", "milivolt pe minut"),
        ("H63", "miligram pe centimetru pătrat"),
        ("H64", "miligram pe gram"),
        ("H65", "mililitru pe metru cub"),
        ("H66", "milimetru pe an"),
        ("H67", "milimetru pe oră"),
        ("H68", "milimol pe gram"),
        ("H69", "picopascal pe kilometru"),
        ("H70", "picosecundă"),
        ("H71", "procent pe lună"),
        ("H72", "procent pe hectobar"),
        ("H73", "procent pe decakelvin"),
        ("H74", "watt pe metru"),
        ("H75", "decapascal"),
        ("H76", "gram pe milimetru"),
        ("H77", "lățime modul"),
        ("H79", "ecartament metric"),
        ("H80", "unitate rack"),
        ("H81", "milimetru pe minut"),
        ("H82", "big point"),
        ("H83", "litru pe kilogram"),
        ("H84", "gram milimetru"),
        ("H85", "săptămână reciprocă"),
        ("H87", "bucată"),
        ("H88", "megaohm kilometru"),
        ("H89", "procent pe ohm"),
        ("H90", "procent pe grad"),
        ("H91", "procent la zece mii"),
        ("H92", "procent la o sută de mii"),
        ("H93", "procent la sută"),
        ("H94", "procent la mie"),
        ("H95", "procent pe volt"),
        ("H96", "procent pe bar"),
        ("H98", "procent pe inch"),
        ("H99", "procent pe metru"),
        ("HA", "hank"),
        ("HBA", "hectobar"),
        ("HBX", "o sută de cutii"),
        ("HC", "numărătoare până la o sută"),
        ("HDW", "o sută de kilograme, greutate uscată"),
        ("HEA", "cap"),
        ("HGM", "hectogram"),
        ("HH", "picior sută cub"),
        ("HIU", "unitate internațională pentru sută"),
        ("HKM", "o sută de kilograme, masă netă"),
        ("HLT", "hectolitru"),
        ("HM", "milă pe oră (milă statutară)"),
        ("HMQ", "milioane de metri cubi"),
        ("HMT", "hectometru"),
        ("HPA", "hectolitru de alcool pur"),
        ("HTZ", "hertz"),
        ("HUR", "oră"),
        ("IA", "inch pound (liră inch)"),
        ("IE", "persoană"),
        ("INH", "inch"),
        ("INK", "inch pătrat"),
        ("INQ", "inch cub"),
        ("ISD", "scala internațională de zahăr"),
        ("IU", "inch pe secundă"),
        ("IUG", "unitate internațională pe gram"),
        ("IV", "inch pe secundă pătrat"),
        ("J10", "procente pe milimetru"),
        ("J12", "pe mil pe psi"),
        ("J13", "gradul API"),
        ("J14", "gradul Baume (scala de origine)"),
        ("J15", "grad Baume (grea din SUA)"),
        ("J16", "grad Baume (lumină SUA)"),
        ("J17", "grad Balling"),
        ("J18", "grad Brix"),
        ("J19", "grade Fahrenheit oră picior pătrat per unitate termică britanică (termochimică)"),
        ("J2", "joule pe kilogram"),
        ("J20", "grad Fahrenheit pe kelvin"),
        ("J21", "grade Fahrenheit pe bar"),
        ("J22", "grade Fahrenheit oră picior pătrat per unitate termică britanică (tabel internațional)"),
        ("J23", "grade Fahrenheit pe oră"),
        ("J24", "grade Fahrenheit pe minut"),
        ("J25", "grade Fahrenheit pe secundă"),
        ("J26", "grad reciproc Fahrenheit"),
        ("J27", "grad Oechsle"),
        ("J28", "grad Rankine pe oră"),
        ("J29", "grad Rankine pe minut"),
        ("J30", "grad Rankine pe secundă"),
        ("J31", "grad Twaddell"),
        ("J32", "micropoise"),
        ("J33", "microgram pe kilogram"),
        ("J34", "microgram pe metru cub kelvin"),
        ("J35", "microgram pe bar metru cub"),
        ("J36", "microlitru pe litru"),
        ("J38", "baud"),
        ("J39", "unitate termică britanică (medie)"),
        ("J40", "Unitate termică britanică (masă internațională) picior pe oră grad Fahrenheit de picior pătrat"),
        ("J41", "Unitate termică britanică (masă internațională) inchi pe oră grade Fahrenheit de picior pătrat"),
        ("J42", "Unitate termică britanică (masă internațională) inchi pe secundă grade Fahrenheit de picior pătrat"),
        ("J43", "Unitate termică britanică (tabel internațional) per liră grad Fahrenheit"),
        ("J44", "Unitate termică britanică (masă internațională) pe minut"),
        ("J45", "Unitate termică britanică (tabel internațional) pe secundă"),
        ("J46", "Unitate termică britanică (termochimică) picior pe oră grade Fahrenheit de picior pătrat"),
        ("J47", "Unitate termică britanică (termochimică) pe oră"),
        ("J48", "Unitate termică britanică (termochimică) inchi pe oră grade Fahrenheit de picior pătrat"),
        ("J49", "Unitate termică britanică (termochimică) inchi pe secundă grade Fahrenheit picior pătrat"),
        ("J50", "Unitate termică britanică (termochimică) pe liră grad Fahrenheit"),
        ("J51", "Unitate termică britanică (termochimică) pe minut"),
        ("J52", "Unitate termică britanică (termochimică) pe minut"),
        ("J53", "coulomb metru pătrat pe kilogram"),
        ("J54", "megabaud"),
        ("J55", "watt secundă"),
        ("J56", "bar pe bar"),
        ("J57", "baril (petrol din Marea Britanie)"),
        ("J58", "baril (petrol din Marea Britanie) pe minut"),
        ("J59", "baril (petrol din Marea Britanie) pe zi"),
        ("J60", "baril (petrol din Marea Britanie) pe oră"),
        ("J61", "baril (petrol din Marea Britanie) pe secundă"),
        ("J62", "baril (petrol american) pe oră"),
        ("J63", "baril (petrol american) pe secundă"),
        ("J64", "bushel (Marea Britanie) pe zi"),
        ("J65", "bushel (Marea Britanie) pe oră"),
        ("J66", "bushel (Marea Britanie) pe minut"),
        ("J67", "bushel (Marea Britanie) pe secundă"),
        ("J68", "bushel (material uscat SUA) pe zi"),
        ("J69", "bushel (material uscat SUA) pe oră"),
        ("J70", "bushel (material uscat SUA) pe minut"),
        ("J71", "bushel (material uscat SUA) pe secundă"),
        ("J72", "centinewton metru"),
        ("J73", "centipoise pe kelvin"),
        ("J74", "centipoise pe bar"),
        ("J75", "calorie (medie)"),
        ("J76", "calorii (tabel internațional) pe gram grad Celsius"),
        ("J78", "calorii (termochimic) pe centimetru gradul II Celsius"),
        ("J79", "calorii (termochimic) pe gram grad Celsius"),
        ("J81", "calorii (termochimic) pe minut"),
        ("J82", "calorii (termochimic) pe secundă"),
        ("J83", "clo"),
        ("J84", "centimetru pe secundă kelvin"),
        ("J85", "bar centimetru pe secundă"),
        ("J87", "centimetru cub pe metru cub"),
        ("J90", "decimetru cub pe zi"),
        ("J91", "decimetru cub pe metru cub"),
        ("J92", "decimetru cub pe minut"),
        ("J93", "decimetru cub pe secundă"),
        ("J95", "uncie (lichid Marea Britanie) pe zi"),
        ("J96", "uncie (lichid Marea Britanie) pe oră"),
        ("J97", "uncie (lichid Marea Britanie) pe minut"),
        ("J98", "uncie (lichid Marea Britanie) pe secundă"),
        ("J99", "uncie (lichid american) pe zi"),
        ("JE", "joule pe kelvin"),
        ("JK", "megajoule pe kilogram"),
        ("JM", "megajoule pe metru cub"),
        ("JNT", "conductă de date comună"),
        ("JOU", "joule"),
        ("JPS", "sută de metri"),
        ("JWL", "număr rubine"),
        ("K1", "cerere de kilowați"),
        ("K10", "uncie (lichid american) pe oră"),
        ("K11", "uncie (lichid SUA) pe minut"),
        ("K12", "uncie (lichid SUA) pe secundă"),
        ("K13", "picior pe grad Fahrenheit"),
        ("K14", "picior pe oră"),
        ("K15", "picior livră-forță pe oră"),
        ("K16", "picior livră-forță pe minut"),
        ("K17", "picior per psi"),
        ("K18", "picior pe gradul secund Fahrenheit"),
        ("K19", "picior pe secundă psi"),
        ("K2", "cerere reactivă kilovolt amperi"),
        ("K20", "picior cub reciproc"),
        ("K21", "picior cub pe grad Fahrenheit"),
        ("K22", "picior cub pe zi"),
        ("K23", "picior cub per psi"),
        ("K26", "galon (Marea Britanie) pe zi"),
        ("K27", "gallon (UK) pe oră"),
        ("K28", "galon (Marea Britanie) pe secundă"),
        ("K3", "kilovolt amperi reactiv oră"),
        ("K30", "galon (lichid SUA) pe secundă"),
        ("K31", "gram-forță pe centimetru pătrat"),
        ("K32", "gil (Marea Britanie) pe zi"),
        ("K33", "gil (Marea Britanie) pe oră"),
        ("K34", "gil (Marea Britanie) pe minut"),
        ("K35", "gil (Marea Britanie) pe secundă"),
        ("K36", "gil (Marea Britanie) pe zi"),
        ("K37", "gil (Marea Britanie) pe oră"),
        ("K38", "gil (Marea Britanie) pe minut"),
        ("K39", "gil (Marea Britanie) pe secundă"),
        ("K40", "accelerația standard a căderii libere"),
        ("K41", "cereale per galon (SUA)"),
        ("K42", "cai putere (cazan)"),
        ("K43", "cai putere (electric)"),
        ("K45", "inch pe grad Fahrenheit"),
        ("K46", "inch per psi"),
        ("K47", "inci pe două grade Fahrenheit"),
        ("K48", "inch pe secundă psi"),
        ("K49", "inch cubi reciproc"),
        ("K50", "kilobaud"),
        ("K51", "kilocalorie (medie)"),
        ("K52", "kilocalorie (tabel internațional) pe oră metru grad Celsius"),
        ("K53", "kilocalorie (termochimic)"),
        ("K54", "kilocalorii (termochimic) pe minut"),
        ("K55", "kilocalorii (termochimice) pe secundă"),
        ("K58", "kilomol pe oră"),
        ("K59", "kilomol pe metru cub kelvin"),
        ("K6", "kilolitru"),
        ("K60", "kilomol pe bar metru cub"),
        ("K61", "kilomol pe minut"),
        ("K62", "litru pe litru"),
        ("K63", "litru reciproc"),
        ("K64", "liră (avoirdupois) pe grad Fahrenheit"),
        ("K65", "liră (avoirdupois) picior pătrat"),
        ("K66", "liră (avoirdupois) pe zi"),
        ("K67", "liră pe picior oră"),
        ("K68", "liră pe picior secundă"),
        ("K69", "liră (avoirdupois) pe picior cub grad Fahrenheit"),
        ("K70", "liră (avoirdupois) per picior cub psi"),
        ("K71", "liră (avoirdupois) per galon (Marea Britanie)"),
        ("K73", "liră (avoirdupois) pe oră grad Fahrenheit"),
        ("K74", "liră (avoirdupois) pe oră psi"),
        ("K75", "liră (avoirdupois) pe inch cubic grad Fahrenheit"),
        ("K76", "liră (avoirdupois) per inch cubic psi"),
        ("K77", "liră (avoirdupois) per psi"),
        ("K78", "liră (avoirdupois) pe minut"),
        ("K79", "liră (avoirdupois) pe minut grad Fahrenheit"),
        ("K80", "liră (avoirdupois) pe minut psi"),
        ("K81", "liră (avoirdupois) pe secundă"),
        ("K82", "liră (avoirdupois) pe gradul secund Fahrenheit"),
        ("K83", "liră (avoirdupois) pe secundă psi"),
        ("K84", "liră pe yard cub"),
        ("K85", "liră-forță pe metru pătrat"),
        ("K86", "liră-forță pe inch pătrat grad Fahrenheit"),
        ("K87", "psi inch cubi pe secundă"),
        ("K88", "psi litru pe secundă"),
        ("K89", "psi metru cub pe secundă"),
        ("K90", "psi yard cubi pe secundă"),
        ("K91", "liră-forță secundă pe metru pătrat"),
        ("K92", "liră-forță secundă pe inch pătrat"),
        ("K93", "psi reciprocă"),
        ("K94", "quart (lichid Marea Britanie) pe zi"),
        ("K95", "quart (lichid Marea Britanie) pe oră"),
        ("K96", "quart (lichid Marea Britanie) pe minut"),
        ("K97", "quart (lichid Marea Britanie) pe secundă"),
        ("K98", "quart (lichid SUA) pe zi"),
        ("K99", "quart (lichid SUA) pe oră"),
        ("KA", "cake (unitate de măsură volumică)"),
        ("KAT", "katal"),
        ("KB", "kilocaracter"),
        ("KBA", "kilobar"),
        ("KCC", "kilogram de clorură de colină"),
        ("KDW", "kilogram greutate netă scursă"),
        ("KEL", "kelvin"),
        ("KGM", "kilogram"),
        ("KGS", "kilogram pe secundă"),
        ("KHY", "kilogram de peroxid de hidrogen"),
        ("KHZ", "kilohertz"),
        ("KI", "kilogram pe milimetru lățime"),
        ("KIC", "kilogram, inclusiv container"),
        ("KIP", "kilogram, inclusiv ambalajul interior"),
        ("KJ", "kilosegment"),
        ("KJO", "kilojoule"),
        ("KL", "kilogram pe metru"),
        ("KLK", "procent de material uscat lactic"),
        ("KLX", "kilolux"),
        ("KMA", "kilogram de metilamină"),
        ("KMH", "kilometru pe oră"),
        ("KMK", "kilometru pătrat"),
        ("KMQ", "kilogram pe metru cub"),
        ("KMT", "kilometru"),
        ("KNI", "kilogram de azot"),
        ("KNM", "kilonewton pe metru pătrat"),
        ("KNS", "substanță numită kilogram"),
        ("KNT", "nod"),
        ("KO", "potasiu caustic miliechivalență per gram de produs"),
        ("KPA", "kilopascal"),
        ("KPH", "kilogram de hidroxid de potasiu (potasiu caustic)"),
        ("KPO", "kilogram de oxid de potasiu"),
        ("KPP", "kilogram de pentoxid de fosfor (anhidridă fosforică)"),
        ("KR", "kiloroentgen"),
        ("KSD", "kilogram de substanță 90 % uscată"),
        ("KSH", "kilogram de hidroxid de sodiu (sodă caustică)"),
        ("KT", "kit"),
        ("KTN", "kilotone"),
        ("KUR", "kilogram de uraniu"),
        ("KVA", "kilovolt - amper"),
        ("KVR", "kilovar"),
        ("KVT", "kilovolt"),
        ("KW", "kilogram pe milimetru"),
        ("KWH", "kilowatt oră"),
        ("KWN", "Kilowatt-oră pe metru cub normalizat"),
        ("KWO", "kilogram de trioxid de wolfram"),
        ("KWS", "Kilowatt-oră pe metru cub standard"),
        ("KWT", "kilowatt"),
        ("KX", "mililitru pe kilogram"),
        ("L10", "quart (lichid SUA) pe minut"),
        ("L11", "quart (lichid din SUA) pe secundă"),
        ("L12", "metru pe secundă kelvin"),
        ("L13", "metru pe secundă bar"),
        ("L14", "metru pătrat oră grad Celsius pe kilocalorie (tabel internațional)"),
        ("L15", "milipascal secundă pe kelvin"),
        ("L16", "milipascal secundă pe bar"),
        ("L17", "miligram pe metru cub kelvin"),
        ("L18", "miligram pe bar metru cub"),
        ("L19", "mililitru pe litru"),
        ("L2", "litru pe minut"),
        ("L20", "milimetru cub reciproc"),
        ("L21", "milimetru cub pe metru cub"),
        ("L23", "mol pe oră"),
        ("L24", "mol pe kilogram kelvin"),
        ("L25", "mol pe kilogram bar"),
        ("L26", "mol pe litru kelvin"),
        ("L27", "mol pe litru bar"),
        ("L28", "mol pe metru cub kelvin"),
        ("L29", "mol pe metru cub bar"),
        ("L30", "mol pe minut"),
        ("L31", "milliroentgen echivalent in roentgen"),
        ("L32", "nanogram pe kilogram"),
        ("L33", "uncie (avoirdupois) pe zi"),
        ("L34", "uncie (avoirdupois) pe oră"),
        ("L35", "uncie (avoirdupois) pe minut"),
        ("L36", "uncie (avoirdupois) pe secundă"),
        ("L37", "uncie (avoirdupois) pe galon (Marea Britanie)"),
        ("L38", "uncie (avoirdupois) pe galon (SUA)"),
        ("L39", "uncie (avoirdupois) pe inch cubic"),
        ("L40", "uncie (avoirdupois)-forță"),
        ("L41", "uncie (avoirdupois)-forță inch"),
        ("L42", "picosiemens pe metru"),
        ("L43", "peck (Marea Britanie) (unitate de capacitate)"),
        ("L44", "peck (Marea Britanie) pe zi"),
        ("L45", "peck (Marea Britanie) pe oră"),
        ("L46", "peck (Marea Britanie) pe minut"),
        ("L47", "peck (Marea Britanie) pe secundă"),
        ("L48", "peck (material uscat Marea Britanie) pe zi"),
        ("L49", "peck (material uscat Marea Britanie) pe oră"),
        ("L50", "peck (material uscat Marea Britanie) pe minut"),
        ("L51", "peck (material uscat Marea Britanie) pe secundă"),
        ("L52", "psi pe psi"),
        ("L53", "pint (Marea Britanie) pe zi"),
        ("L54", "pint (Marea Britanie) pe oră"),
        ("L55", "pint (Marea Britanie) pe minut"),
        ("L56", "pint (Marea Britanie) pe secundă"),
        ("L57", "pint (lichid Marea Britanie) pe zi"),
        ("L58", "pint (lichid Marea Britanie) pe oră"),
        ("L59", "pint (lichid Marea Britanie) pe minut"),
        ("L60", "pint (lichid Marea Britanie) pe secundă"),
        ("L63", "slug pe zi"),
        ("L64", "slug pe picior secundă"),
        ("L65", "slug pe picior cub"),
        ("L66", "slug pe oră"),
        ("L67", "slug pe minut"),
        ("L68", "slug pe secundă"),
        ("L69", "tonă pe kelvin"),
        ("L70", "tonă pe bar"),
        ("L71", "tonă pe zi"),
        ("L72", "tonă pe zi kelvin"),
        ("L73", "tonă pe zi bar"),
        ("L74", "tonă pe oră kelvin"),
        ("L75", "tonă pe oră bar"),
        ("L76", "tonă pe metru cub kelvin"),
        ("L77", "tonă pe metru cub bar"),
        ("L78", "tonă pe minut"),
        ("L79", "tonă pe minut kelvin"),
        ("L80", "tonă pe minut bar"),
        ("L81", "tonă pe secundă"),
        ("L82", "tonă pe secundă kelvin"),
        ("L83", "tonă pe secundă bar"),
        ("L84", "tonă (livrare în Marea Britanie)"),
        ("L85", "tonă lungă pe zi"),
        ("L86", "tonă (livrare în SUA)"),
        ("L87", "tonă scurtă pe grad Fahrenheit"),
        ("L88", "tonă scurtă pe zi"),
        ("L89", "tonă scurtă pe oră grade Fahrenheit"),
        ("L90", "tonă scurtă pe oră psi"),
        ("L91", "tonă scurtă per psi"),
        ("L92", "tonă (lungime în Marea Britanie) pe yard cub"),
        ("L93", "tonă (scurt din SUA) pe yard cub"),
        ("L94", "tonă-forță (scurt în SUA)"),
        ("L95", "an comun"),
        ("L96", "an sideral"),
        ("L98", "iard pe grad Fahrenheit"),
        ("L99", "iard pe psi"),
        ("LA", "liră pe inch cub"),
        ("LAC", "procentul de exces de lactoză"),
        ("LBR", "liră"),
        ("LBT", "lira troy (SUA)"),
        ("LD", "litru pe zi"),
        ("LEF", "cadru"),
        ("LF", "picior liniar"),
        ("LH", "oră de muncă"),
        ("LK", "legătură"),
        ("LM", "metru liniar"),
        ("LN", "lungime"),
        ("LO", "lot [unitate de achiziție]"),
        ("LP", "liră lichidă"),
        ("LPA", "litru de alcool pur"),
        ("LR", "nivel"),
        ("LS", "sumă forfetară"),
        ("LTN", "tonă (Marea Britanie) sau tonă lungă (SUA)"),
        ("LTR", "litru"),
        ("LUB", "tonă metrică, ulei lubrifiant"),
        ("LUM", "lumen"),
        ("LUX", "lux"),
        ("LY", "iard liniar"),
        ("M1", "miligram pe litru"),
        ("M10", "iard cubic reciproc"),
        ("M11", "iard cubic pe grad Fahrenheit"),
        ("M12", "iard cubic pe zi"),
        ("M13", "iard cubic pe oră"),
        ("M14", "iard cubic pe psi"),
        ("M15", "iard cubic pe minut"),
        ("M16", "iard cubic pe secundă"),
        ("M17", "metru kilohertzi"),
        ("M18", "metru gigahertzi"),
        ("M19", "Beaufort"),
        ("M20", "megakelvin reciproc sau megakelvin la puterea minus unu"),
        ("M21", "kilovolt reciproc - amperi oră reciprocă"),
        ("M22", "mililitru pe centimetru pătrat minut"),
        ("M23", "newton pe centimetru"),
        ("M24", "ohm kilometru"),
        ("M25", "procente pe grad Celsius"),
        ("M26", "gigaohm pe metru"),
        ("M27", "metru megahertzi"),
        ("M29", "kilogram pe kilogram"),
        ("M30", "volt reciproc - amper secundă reciprocă"),
        ("M31", "kilogram pe kilometru"),
        ("M32", "pascal secundă pe litru"),
        ("M33", "milimol pe litru"),
        ("M34", "metru newton pe metru pătrat"),
        ("M35", "milivolt - amper"),
        ("M36", "luna de 30 de zile"),
        ("M37", "actual/360"),
        ("M38", "kilometru pe secundă pătrat"),
        ("M39", "centimetru pe secundă pătrat"),
        ("M4", "valoare monetară"),
        ("M40", "iard pe secundă pătrat"),
        ("M41", "milimetru pe secundă pătrat"),
        ("M42", "milă (milă statutară) pe secundă pătrat"),
        ("M43", "mil"),
        ("M44", "revoluție"),
        ("M45", "grad [unitate de unghi] pe secundă pătrat"),
        ("M46", "revoluție pe minut"),
        ("M47", "mil circular"),
        ("M48", "milă pătrată (pe baza piciorului de sondaj din SUA)"),
        ("M49", "lanț (bazat pe piciorul sondajului din SUA)"),
        ("M5", "microcurie"),
        ("M50", "furlong"),
        ("M51", "picior (sondaj din SUA)"),
        ("M52", "milă (pe baza piciorului de sondaj din SUA)"),
        ("M53", "metru pe pascal"),
        ("M55", "metru pe radiant"),
        ("M56", "shake"),
        ("M57", "milă pe minut"),
        ("M58", "milă pe secundă"),
        ("M59", "metru pe secundă pascal"),
        ("M60", "metru pe oră"),
        ("M61", "inch pe an"),
        ("M62", "kilometru pe secundă"),
        ("M63", "inch pe minut"),
        ("M64", "iard pe secundă"),
        ("M65", "iard pe minut"),
        ("M66", "iard pe oră"),
        ("M67", "acre-foot (bazat pe piciorul sondajului din SUA)"),
        ("M68", "cord (128 ft3) (volum material uscat)"),
        ("M69", "mile cubice (statutul Regatului Unit)"),
        ("M7", "micro-inch"),
        ("M70", "tonaj, registru"),
        ("M71", "metru cub pe pascal"),
        ("M72", "bel"),
        ("M73", "kilogram pe metru cub pascal"),
        ("M74", "kilogram pe pascal"),
        ("M75", "kilopound-forță"),
        ("M76", "poundal"),
        ("M77", "kilogram metru pe secundă pătrat"),
        ("M78", "bazin"),
        ("M79", "picior pătrat pe oră"),
        ("M80", "stokes per pascal"),
        ("M81", "centimetru pătrat pe secundă"),
        ("M82", "metru pătrat pe secundă pascal"),
        ("M83", "denier"),
        ("M84", "lira pe iard"),
        ("M85", "tonă, masă"),
        ("M86", "pfund"),
        ("M87", "kilogram pe secundă pascal"),
        ("M88", "tonă pe lună"),
        ("M89", "tonă pe an"),
        ("M9", "milioane Btu la 1000 de picioare cub"),
        ("M90", "kilopound pe oră"),
        ("M91", "liră pe liră"),
        ("M92", "picior de liră-forță"),
        ("M93", "newton metru pe radian"),
        ("M94", "kilogram metru"),
        ("M95", "picior poundal"),
        ("M96", "inch poundal"),
        ("M97", "metru dină"),
        ("M98", "kilogram centimetru pe secundă"),
        ("M99", "gram centimetru pe secundă"),
        ("MAH", "megavolt amperi oră reactivă"),
        ("MAL", "megalitru"),
        ("MAM", "megametru"),
        ("MAR", "megavar"),
        ("MAW", "megawatt"),
        ("MBE", "mii echivalent caramida standard"),
        ("MBF", "mii de picior de scândură"),
        ("MBR", "milibar"),
        ("MC", "microgram"),
        ("MCU", "milicurie"),
        ("MD", "tonă metrică uscată la aer"),
        ("MGM", "miligram"),
        ("MHZ", "megahertz"),
        ("MIK", "milă pătrată (milă statutară)"),
        ("MIL", "milă pătrată (milă statutară) mii"),
        ("MIN", "minut [unitate de timp]"),
        ("MIO", "milion"),
        ("MIU", "milioane de unități internaționale"),
        ("MLD", "miliard"),
        ("MLT", "mililitru"),
        ("MMK", "milimetru pătrat"),
        ("MMQ", "milimetru cub"),
        ("MMT", "milimetru"),
        ("MND", "kilogram, greutate uscată"),
        ("MON", "lună"),
        ("MPA", "megapascal"),
        ("MQH", "metru cub pe oră"),
        ("MQS", "metru cub pe secundă"),
        ("MSK", "metru pe secundă pătrat"),
        ("MTK", "metru pătrat"),
        ("MTQ", "metru cub"),
        ("MTR", "metru"),
        ("MTS", "metru pe secundă"),
        ("MVA", "megavolt - amper"),
        ("MWH", "megawați oră (1000 kW.h)"),
        ("N1", "calorie pen"),
        ("N10", "liră picior pe secundă"),
        ("N11", "liră inch pe secundă"),
        ("N12", "cai putere"),
        ("N13", "centimetru de mercur (0°C)"),
        ("N14", "centimetru de apă (4 ºC)"),
        ("N15", "picior de apă (39,2 ºF)"),
        ("N16", "inch de mercur (32 °F)"),
        ("N17", "inch de mercur (60 °F)"),
        ("N18", "inch de apă (39,2 °F)"),
        ("N19", "inch de apă (60 °F)"),
        ("N20", "kip pe inch pătrat"),
        ("N21", "lire pe picior pătrat"),
        ("N22", "uncie (avoirdupois) pe inch pătrat"),
        ("N23", "metru convențional de apă"),
        ("N24", "gram pe milimetru pătrat"),
        ("N25", "liră pe iard pătrat"),
        ("N26", "poundal pe inch pătrat"),
        ("N27", "piciorul la puterea a patra"),
        ("N28", "decimetru cubic pe kilogram"),
        ("N29", "picior cubic pe kilogram"),
        ("N3", "punct imprimare"),
        ("N30", "inch cub pe kilogram"),
        ("N31", "kilonewton pe metru"),
        ("N32", "lire pe inch"),
        ("N33", "liră-forță pe yard"),
        ("N34", "liră secundă pe picior pătrat"),
        ("N35", "poise pe pascal"),
        ("N36", "newton secundă pe metru pătrat"),
        ("N37", "kilogram pe metru secundă"),
        ("N38", "kilogram pe metru minut"),
        ("N39", "kilogram pe metru zi"),
        ("N40", "kilogram pe metru oră"),
        ("N41", "gram pe secundă centimetru"),
        ("N42", "liră secundă pe inch pătrat"),
        ("N43", "liră pe picior minut"),
        ("N44", "liră pe picior pe zi"),
        ("N45", "metru cub pe secundă pascal"),
        ("N46", "picior poundal"),
        ("N47", "inch poundal"),
        ("N48", "wați pe centimetru pătrat"),
        ("N49", "watt pe inch pătrat"),
        ("N50", "Unitate termică britanică (masă internațională) pe picior pătrat oră"),
        ("N51", "Unitate termică britanică (termochimică) pe metru pătrat oră"),
        ("N52", "Unitate termică britanică (termochimică) pe minut de metru pătrat"),
        ("N53", "Unitate termică britanică (tabel internațional) pe metru pătrat secundă"),
        ("N54", "Unitate termică britanică (termochimică) pe metru pătrat secundă"),
        ("N55", "Unitate termică britanică (tabel internațional) pe secundă inch pătrat"),
        ("N56", "calorie (thermochemical) pe centimetru cub minut"),
        ("N57", "calorii (termochimice) pe centimetru pătrat secundă"),
        ("N58", "Unitate termică britanică (tabel internațional) pe picior cub"),
        ("N59", "Unitate termică britanică (termochimică) pe picior cub"),
        ("N60", "Unitate termică britanică (tabel internațional) pe grad Fahrenheit"),
        ("N61", "Unitate termică britanică (termochimică) pe grad Fahrenheit"),
        ("N62", "Unitate termică britanică (tabel internațional) pe grad Rankine"),
        ("N63", "Unitate termică britanică (termochimică) pe grad Rankine"),
        ("N64", "Unitate termică britanică (termochimică) pe liră grad Rankine"),
        ("N65", "kilocalorie (tabel internațional) per gram kelvin"),
        ("N66", "Unitate termică britanică (39 °F)"),
        ("N67", "Unitate termică britanică (59 °F)"),
        ("N68", "Unitate termică britanică (60 °F)"),
        ("N69", "calorii (20 ºC)"),
        ("N70", "quad (1015 BtuIT)"),
        ("N71", "therm (EC)"),
        ("N72", "therm (U.S.)"),
        ("N73", "Unitate termică britanică (termochimică) pe kilogram"),
        ("N74", "Unitate termică britanică (tabel internațional) pe oră picior pătrat grad Fahrenheit"),
        ("N75", "Unitate termică britanică (termochimică) pe oră grade Fahrenheit de picior pătrat"),
        ("N76", "Unitate termică britanică (tabel internațional) pe secundă picior pătrat grad Fahrenheit"),
        ("N77", "Unitate termică britanică (termochimică) pe secundă picior pătrat grad Fahrenheit"),
        ("N78", "kilowatt pe metru pătrat kelvin"),
        ("N79", "kelvin pe pascal"),
        ("N80", "watt pe metru grad Celsius"),
        ("N81", "kilowatt pe metru kelvin"),
        ("N82", "kilowatt pe metru grad Celsius"),
        ("N83", "metru pe grad Celcius metru"),
        ("N84", "grade Fahrenheit oră per unitate termică britanică (tabel internațional)"),
        ("N85", "grade Fahrenheit oră per unitate termică britanică (termochimică)"),
        ("N86", "grad Fahrenheit secundă per unitate termică britanică (tabel internațional)"),
        ("N87", "grad Fahrenheit secundă per unitate termică britanică (termochimică)"),
        ("N88", "grade Fahrenheit oră picior pătrat per unitate termică britanică (masă internațională) inch"),
        ("N89", "grade Fahrenheit oră picior pătrat per unitate termică britanică (termochimică) inch"),
        ("N90", "kilofarad"),
        ("N91", "joule reciproc"),
        ("N92", "picosiemens"),
        ("N93", "amperi pe pascal"),
        ("N94", "franklin"),
        ("N95", "amper minut"),
        ("N96", "biot"),
        ("N97", "gilbert"),
        ("N98", "volt pe pascal"),
        ("N99", "picovolt"),
        ("NA", "miligram pe kilogram"),
        ("NAR", "număr de articole"),
        ("NCL", "număr de celule"),
        ("NEW", "newton"),
        ("NF", "mesaj"),
        ("NIL", "nil"),
        ("NIU", "numărul de unități internaționale"),
        ("NL", "sarcină"),
        ("NM3", "metru cub normalizat"),
        ("NMI", "milă nautică"),
        ("NMP", "număr de pachete"),
        ("NPT", "numarul de piese"),
        ("NT", "tonă netă"),
        ("NU", "newton metru"),
        ("NX", "parte la mie"),
        ("OA", "panou"),
        ("ODE", "echivalent de epuizare a stratului de ozon"),
        ("ODG", "ODS Grame"),
        ("ODK", "ODS Kilograme"),
        ("ODM", "ODS Miligrame"),
        ("OHM", "ohm"),
        ("ON", "uncie pe iard pătrat"),
        ("ONZ", "uncie (avoirdupois)"),
        ("OPM", "oscilații pe minut"),
        ("OT", "oră suplimentară"),
        ("OZA", "uncie de lichid (SUA)"),
        ("OZI", "uncie de lichid (Marea Britanie)"),
        ("P1", "procent"),
        ("P10", "coulomb pe metru"),
        ("P11", "kiloweber"),
        ("P12", "gamma"),
        ("P13", "kilotesla"),
        ("P14", "joule pe secundă"),
        ("P15", "joule pe minut"),
        ("P16", "joule pe oră"),
        ("P17", "joule pe zi"),
        ("P18", "kilojoule pe secundă"),
        ("P19", "kilojoul pe minut"),
        ("P2", "lira pe picior"),
        ("P20", "kilojoul pe oră"),
        ("P21", "kilojoul pe zi"),
        ("P22", "nanoohm"),
        ("P23", "ohm circular-mil per picior"),
        ("P24", "kilohenry"),
        ("P25", "lumen pe metru pătrat"),
        ("P26", "phot"),
        ("P27", "lumânare-picior"),
        ("P28", "candela pe inch pătrat"),
        ("P29", "footlambert (unitate de luminanță)"),
        ("P30", "lambert"),
        ("P31", "stilb"),
        ("P32", "candela pe metru pătrat"),
        ("P33", "kilocandela"),
        ("P34", "milicandela"),
        ("P35", "Hefner-Kerze"),
        ("P36", "lumânare internațională"),
        ("P37", "Unitate termică britanică (tabel internațional) pe metru pătrat"),
        ("P38", "Unitate termică britanică (termochimică) pe metru pătrat"),
        ("P39", "calorii (termochimice) pe centimetru pătrat"),
        ("P40", "langley  (unitate de transmisie a căldurii)"),
        ("P41", "deceniu (logaritmic)"),
        ("P42", "pascal pătrat secundă"),
        ("P43", "bel pe metru"),
        ("P44", "mol liră"),
        ("P45", "liră mol pe secundă"),
        ("P46", "liră mol pe minut"),
        ("P47", "kilomol pe kilogram"),
        ("P48", "liră mol pe liră"),
        ("P49", "Newton metru pătrat pe amper"),
        ("P5", "pachet de cinci"),
        ("P50", "contor weber"),
        ("P51", "mol pe kilogram pascal"),
        ("P52", "mol pe metru cub pascal"),
        ("P53", "unitate pol"),
        ("P54", "miligray pe secundă"),
        ("P55", "microgray pe secundă"),
        ("P56", "nanogray pe secundă"),
        ("P57", "gray pe minut"),
        ("P58", "miligray pe minut"),
        ("P59", "microgray pe minut"),
        ("P60", "nanogray pe minut"),
        ("P61", "gray pe oră"),
        ("P62", "milligray pe oră"),
        ("P63", "microgray pe oră"),
        ("P64", "nanogray pe oră"),
        ("P65", "sievert pe secundă"),
        ("P66", "milisievert pe secundă"),
        ("P67", "microsievert pe secundă"),
        ("P68", "nanosievert pe secundă"),
        ("P69", "rem pe secundă"),
        ("P70", "sievert pe oră"),
        ("P71", "millisievert pe oră"),
        ("P72", "microsievert pe oră"),
        ("P73", "nanosievert pe oră"),
        ("P74", "sievert pe minut"),
        ("P75", "millisievert pe minut"),
        ("P76", "microsievert pe minut"),
        ("P77", "nanosievert pe minut"),
        ("P78", "inch pătrat reciproc"),
        ("P79", "pascal metru pătrat pe kilogram"),
        ("P80", "milipascal pe metru"),
        ("P81", "kilopascal pe metru"),
        ("P82", "hectopascal pe metru"),
        ("P83", "atmosferă standard pe metru"),
        ("P84", "atmosferă tehnică pe metru"),
        ("P85", "torr pe metru"),
        ("P86", "psi pe inch"),
        ("P87", "metru cub pe secundă metru pătrat"),
        ("P88", "rhe"),
        ("P89", "picior liră-forță pe inch"),
        ("P90", "inch liră-forță pe inch"),
        ("P91", "perm (0 ºC)"),
        ("P92", "perm (0 ºC)"),
        ("P93", "octet pe secundă"),
        ("P94", "kilobyte pe secundă"),
        ("P95", "megabyte pe secundă"),
        ("P96", "volt reciproc"),
        ("P97", "radian reciproc"),
        ("P98", "pascal la suma puterilor numerelor stoichiometrice"),
        ("P99", "mol pe metru cub la suma puterii numerelor stoichiometrice"),
        ("PAL", "pascal"),
        ("PD", "pad"),
        ("PFL", "dovadă-litru"),
        ("PGL", "dovadă-galon"),
        ("PI", "pitch"),
        ("PLA", "grad Platon"),
        ("PO", "liră pe inch de lungime"),
        ("PQ", "pagină pe inch"),
        ("PR", "pereche"),
        ("PS", "liră-forță pe inch pătrat"),
        ("PTD", "pint material uscat (SUA)"),
        ("PTI", "pint (Marea Britanie)"),
        ("PTL", "pint lichid (SUA)"),
        ("PTN", "porție"),
        ("Q10", "joule pe tesla"),
        ("Q11", "erlang"),
        ("Q12", "octet"),
        ("Q13", "octet pe secundă"),
        ("Q14", "shannon"),
        ("Q15", "hartley"),
        ("Q16", "unitate naturală de informaţie"),
        ("Q17", "shannon pe secundă"),
        ("Q18", "hartley pe secundă"),
        ("Q19", "unitate naturală de informație pe secundă"),
        ("Q20", "secundă pe kilogram"),
        ("Q21", "watt metru pătrat"),
        ("Q22", "secundă pe radian metru cub"),
        ("Q23", "weber la puterea minus unu"),
        ("Q24", "inch reciproc"),
        ("Q25", "dioptrie"),
        ("Q26", "unul pe unul"),
        ("Q27", "newton metru pe metru"),
        ("Q28", "kilogram pe metru pătrat pascal secundă"),
        ("Q29", "microgram pe hectogram"),
        ("Q30", "pH (potențial de hidrogen)"),
        ("Q31", "kilojoule pe gram"),
        ("Q32", "femtolitru"),
        ("Q33", "picolitru"),
        ("Q34", "nanolitru"),
        ("Q35", "megawați pe minut"),
        ("Q36", "metru pătrat pe metru cub"),
        ("Q37", "metru cub standard pe zi"),
        ("Q38", "metru cub standard pe oră"),
        ("Q39", "metru cub normalizat pe zi"),
        ("Q40", "metru cub normalizat pe oră"),
        ("Q41", "Joule pe metru cub normalizat"),
        ("Q42", "Joule pe metru cub standard"),
        ("Q3", "masă"),
        ("QA", "pagina - facsimil"),
        ("QAN", "trimestru (de an)"),
        ("QB", "pagină - hârtie"),
        ("QR", "quire"),
        ("QTD", "quart material uscat (SUA)"),
        ("QTI", "quart (Marea Britanie)"),
        ("QTL", "quart lichid (SUA)"),
        ("QTR", "trimestru (Marea Britanie)"),
        ("R1", "pica"),
        ("R9", "mii de metri cubi"),
        ("RH", "oră de funcționare sau de acționare"),
        ("RM", "top"),
        ("ROM", "cameră"),
        ("RP", "coli de hârtie"),
        ("RPM", "rotaţii pe minut"),
        ("RPS", "rotații pe secundă"),
        ("RT", "venit tonă milă"),
        ("S3", "picior pătrat pe secundă"),
        ("S4", "metru pătrat pe secundă"),
        ("SAN", "jumătate de an (6 luni)"),
        ("SCO", "Scor"),
        ("SCR", "scrupul"),
        ("SEC", "secundă [unitate de timp]"),
        ("SET", "set"),
        ("SG", "segment"),
        ("SIE", "siemens"),
        ("SM3", "metru cub standard"),
        ("SMI", "milă (milă statutară)"),
        ("SQ", "pătrat"),
        ("SQR", "pătrat, acoperiș"),
        ("SR", "bandă"),
        ("STC", "stick"),
        ("STI", "piatră (Marea Britanie)"),
        ("STK", "baton, țigară"),
        ("STL", "litru standard"),
        ("STN", "tonă (SUA) sau tonă scurtă (UK/SUA)"),
        ("STW", "paie"),
        ("SW", "skein"),
        ("SX", "expediere"),
        ("SYR", "seringă"),
        ("T0", "linie de telecomunicații în serviciu"),
        ("T3", "o mie de bucăți"),
        ("TAH", "kiloamperi oră (mii de amperi oră)"),
        ("TAN", "număr acid total"),
        ("TI", "mii de inci pătrați"),
        ("TIC", "tonă metrică, inclusiv container"),
        ("TIP", "tonă metrică, inclusiv ambalajul interior"),
        ("TKM", "tonă kilometru"),
        ("TMS", "kilogram de carne de import, mai puține organe"),
        ("TNE", "tonă (tonă metrică)"),
        ("TP", "zece pachete"),
        ("TPI", "dinți pe inch"),
        ("TPR", "zece perechi"),
        ("TQD", "mii de metri cubi pe zi"),
        ("TRL", "trilioane (EUR)"),
        ("TST", "ten set"),
        ("TTS", "zece mii de bețe"),
        ("U1", "tratament"),
        ("U2", "comprimat"),
        ("UB", "linie de telecomunicații în medie de serviciu"),
        ("UC", "portul de telecomunicații"),
        ("VA", "volt - amperi pe kilogram"),
        ("VLT", "volt"),
        ("VP", "volum procentual"),
        ("W2", "kilogram material umed"),
        ("WA", "watt pe kilogram"),
        ("WB", "liră materail umed"),
        ("WCD", "cordon"),
        ("WE", "tonă material umed"),
        ("WEB", "weber"),
        ("WEE", "săptămână"),
        ("WG", "galon de vin"),
        ("WHR", "watt oră"),
        ("WM", "lună de lucru"),
        ("WSD", "standard"),
        ("WTT", "watt"),
        ("X1", "Lanțul lui Gunter"),
        ("YDK", "yard pătrat"),
        ("YDQ", "yard cubic"),
        ("YRD", "yard"),
        ("Z11", "container suspendat"),
        ("ZP", "pagină"),
        ("ZZ", "definite reciproc"),
        ("X1A", "Tambur, oțel"),
        ("X1B", "Tambur, aluminiu"),
        ("X1D", "Tambur, placaj"),
        ("X1F", "Container, flexibil"),
        ("X1G", "Tambur, fibră"),
        ("X1W", "Tambur, lemn"),
        ("X2C", "Butoi, lemn"),
        ("X3A", "Jerican, oțel"),
        ("X3H", "Jerrican, plastic"),
        ("X43", "Cutie, super vrac"),
        ("X44", "Cutie, pungă de polietilenă"),
        ("X4A", "Cutie, oțel"),
        ("X4B", "Cutie, aluminiu"),
        ("X4C", "Cutie, lemn natural"),
        ("X4D", "Cutie, placaj"),
        ("X4F", "Cutie, lemn reconstituit"),
        ("X4G", "Cutie, placă de fibre"),
        ("X4H", "Cutie, plastic"),
        ("X5H", "Geantă, plastic țesut"),
        ("X5L", "Cutie, textil"),
        ("X5M", "Cutie, hârtie"),
        ("X6H", "Ambalaj compozit, recipient din plastic"),
        ("X6P", "Ambalaj compozit, recipient din sticlă"),
        ("X7A", "Carcasă, mașină"),
        ("X7B", "Carcasă, lemn"),
        ("X8A", "Palet, lemn"),
        ("X8B", "Ladă, lemn"),
        ("X8C", "Pachet, din lemn"),
        ("XAA", "Container intermediar pentru vrac, plastic rigid"),
        ("XAB", "Recipient, fibră"),
        ("XAC", "Recipient, hârtie"),
        ("XAD", "Recipient, din lemn"),
        ("XAE", "Aerosol"),
        ("XAF", "Palet, modular, gulere 80cms * 60cms"),
        ("XAG", "Palet, ambalat"),
        ("XAH", "Palet, 100 cm * 110 cm"),
        ("XAI", "Clapetă"),
        ("XAJ", "Con"),
        ("XAL", "Ball"),
        ("XAM", "Fiolă, neprotejată"),
        ("XAP", "Fiolă, protejată"),
        ("XAT", "Pulverizator"),
        ("XAV", "Capsulă"),
        ("XB4", "Centura"),
        ("XBA", "Butoi"),
        ("XBB", "Bobină"),
        ("XBC", "Ladă pentru sticle / suport pentru sticle"),
        ("XBD", "Bord"),
        ("XBE", "Pachet"),
        ("XBF", "Balon, neprotejat"),
        ("XBG", "Geanta"),
        ("XBH", "Buchet"),
        ("XBI", "Coș"),
        ("XBJ", "Găleată"),
        ("XBK", "Coș"),
        ("XBL", "Bale, comprimat"),
        ("XBM", "Bazin"),
        ("XBN", "Bale, necomprimate"),
        ("XBO", "Flacon, neprotejat, cilindric"),
        ("XBP", "Balon, protejat"),
        ("XBQ", "Flacon, cilindric protejat"),
        ("XBR", "Bar"),
        ("XBS", "Flacon, neprotejat, bulbos"),
        ("XBT", "Bolt"),
        ("XBU", "Butoi"),
        ("XBV", "Sticlă, bulboasă protejată"),
        ("XBW", "Cutie, pentru lichide"),
        ("XBX", "Cutie"),
        ("XBY", "Scândură, în legătură/mănunchi/îngrijit"),
        ("XBZ", "Bare, în legătură/mănunchi/îngrijit"),
        ("XCA", "Cutie, dreptunghiulară"),
        ("XCB", "Ladă, bere"),
        ("XCC", "Putinei"),
        ("XCD", "Bidon, cu mâner și gura de scurgere"),
        ("XCE", "Creel"),
        ("XCF", "Ladă"),
        ("XCG", "Cuşcă"),
        ("XCH", "Cufăr"),
        ("XCI", "Canistră"),
        ("XCJ", "sicriu"),
        ("XCK", "Butoi"),
        ("XCL", "Bobină"),
        ("XCM", "Card"),
        ("XCN", "Container, nespecificat altfel ca echipament de transport"),
        ("XCO", "Bombă, neprotejată"),
        ("XCP", "Bombă, protejată"),
        ("XCQ", "Cartuş"),
        ("XCR", "Ladă"),
        ("XCS", "Caz"),
        ("XCT", "Cutie de carton"),
        ("XCU", "Ceașcă"),
        ("XCV", "Capac"),
        ("XCW", "Cușcă, rolă"),
        ("XCX", "Bidon, cilindric"),
        ("XCY", "Cilindru"),
        ("XCZ", "Pânză"),
        ("XDA", "Ladă, mai multe straturi, plastic"),
        ("XDB", "Ladă, mai multe straturi, din lemn"),
        ("XDC", "Ladă, mai multe straturi, carton"),
        ("XDG", "Cage, Commonwealth Handling Equipment Pool (CHEP)"),
        ("XDH", "Box, Commonwealth Handling Equipment Pool (CHEP), Eurobox"),
        ("XDI", "Tambur, fier de călcat"),
        ("XDJ", "Bomiana, neprotejat"),
        ("XDK", "Ladă, vrac, carton"),
        ("XDL", "Ladă, vrac, plastic"),
        ("XDM", "Ladă, vrac, lemn"),
        ("XDN", "Dozator"),
        ("XDP", "Damijohn, protejat"),
        ("XDR", "Tambur"),
        ("XDS", "Tavă, un strat fără capac, plastic"),
        ("XDT", "Tavă, un strat fără capac, din lemn"),
        ("XDU", "Tavă, un strat fără capac, polistiren"),
        ("XDV", "Tavă, un strat fără capac, carton"),
        ("XDW", "Tavă, două straturi fără capac, tavă din plastic"),
        ("XDX", "Tavă, două straturi fără capac, din lemn"),
        ("XDY", "Tavă, două straturi fără capac, carton"),
        ("XEC", "Geantă, plastic"),
        ("XED", "Carcasă, cu bază de paleți"),
        ("XEE", "Carcasa, cu bază de palet, din lemn"),
        ("XEF", "Carcasă, cu baza de palet, carton"),
        ("XEG", "Carcasă, cu bază de palet, plastic"),
        ("XEH", "Carcasă, cu bază de palet, metal"),
        ("XEI", "Carcasă, izotermă"),
        ("XEN", "Plic"),
        ("XFB", "Flexibag"),
        ("XFC", "Ladă, fructe"),
        ("XFD", "Ladă, înrămată"),
        ("XFE", "Flexitank"),
        ("XFI", "Firkin (unitate de masă)"),
        ("XFL", "Flask"),
        ("XFO", "Footlocker"),
        ("XFP", "Filmpack"),
        ("XFR", "Cadru"),
        ("XFT", "Foodtainer"),
        ("XFW", "Cărucior, plat"),
        ("XFX", "Geantă, recipient flexibil"),
        ("XGB", "Sticlă, gaz"),
        ("XGI", "Grindă"),
        ("XGL", "Recipient, galon"),
        ("XGR", "Recipient, sticlă"),
        ("XGU", "Tavă, care conține articole plate stivuite orizontal"),
        ("XGY", "Geantă, gunny"),
        ("XGZ", "Grinzi, în mănunchi/legătură/îngrijit"),
        ("XHA", "Coș, cu mâner, plastic"),
        ("XHB", "Coș, cu mâner, din lemn"),
        ("XHC", "Coș, cu mâner, carton"),
        ("XHG", "Butoi mare"),
        ("XHN", "Cuier"),
        ("XHR", "Coş"),
        ("XIA", "Pachet, ecran, din lemn"),
        ("XIB", "Pachet, ecran, carton"),
        ("XIC", "Pachet, ecran, plastic"),
        ("XID", "Pachet, ecran, metal"),
        ("XIE", "Pachet, spectacol"),
        ("XIF", "Pachet, curgere"),
        ("XIG", "Pachet, ambalat în hârtie"),
        ("XIH", "Tambur, plastic"),
        ("XIK", "Pachet, carton, cu orificii pentru prindere sticle"),
        ("XIL", "Tavă, rigidă, stivuită cu capac (CEN TS 14482:2002)"),
        ("XIN", "Lingou"),
        ("XIZ", "Lingouri, în legătură/mănunchi/îngrijit"),
        ("XJB", "Geantă, jumbo"),
        ("XJC", "Jerican, dreptunghiular"),
        ("XJG", "Ulcior"),
        ("XJR", "Borcan"),
        ("XJT", "Pungă de iută"),
        ("XJY", "Jerican, cilindric"),
        ("XKG", "Butoi"),
        ("XKI", "Kit"),
        ("XLE", "Bagaj"),
        ("XLG", "Buștean"),
        ("XLT", "Lot"),
        ("XLU", "Lug"),
        ("XLV", "Liftvan"),
        ("XLZ", "Bușteni, în legături/mănunchi/îngrijit"),
        ("XMA", "Ladă, metal"),
        ("XMB", "Pungă, multiplicare"),
        ("XMC", "Ladă, lapte"),
        ("XME", "Container, metal"),
        ("XMR", "Recipient, metalic"),
        ("XMS", "Sac, multi-pereți"),
        ("XMT", "Mat"),
        ("XMW", "Recipient, ambalat din plastic"),
        ("XMX", "Matchbox"),
        ("XNA", "Nu e disponibil"),
        ("XNE", "Despachetat sau neambalat"),
        ("XNF", "Despachetat sau neambalat, o singură unitate"),
        ("XNG", "Despachetate sau neambalat, unități multiple"),
        ("XNS", "Cuib"),
        ("XNT", "Net"),
        ("XNU", "Plasa, tub, plastic"),
        ("XNV", "Plasa, tub, textil"),
        ("XOA", "Palet, CHEP 40 cm x 60 cm"),
        ("XOB", "Palet, CHEP 80 cm x 120 cm"),
        ("XOC", "Palet, CHEP 100 cm x 120 cm"),
        ("XOD", "Palet, AS 4068-1993"),
        ("XOE", "Palet, ISO T11"),
        ("XOF", "Platformă, greutate sau dimensiune nespecificată"),
        ("XOK", "bloc"),
        ("XOT", "Octabin"),
        ("XOU", "Container, exterior"),
        ("XP2", "Tigaie"),
        ("XPA", "Pachet"),
        ("XPB", "Palet, cutie Combinat cutie deschisă și palet"),
        ("XPC", "Colet"),
        ("XPD", "Palet, modular, gulere 80cms * 100cms"),
        ("XPE", "Palet, modular, gulere 80cms * 120cms"),
        ("XPF", "Pix"),
        ("XPG", "Farfurie"),
        ("XPH", "Ulcior"),
        ("XPI", "Țeavă"),
        ("XPJ", "Coşuleţ pentru fructe"),
        ("XPK", "Pachet"),
        ("XPL", "Găleată"),
        ("XPN", "Scândură"),
        ("XPO", "Pungă"),
        ("XPP", "Bucată"),
        ("XPR", "Recipient, plastic"),
        ("XPT", "Oală"),
        ("XPU", "Tavă"),
        ("XPV", "Țevi, în legătură/mănunchi/îngrijit"),
        ("XPX", "Palet"),
        ("XPY", "Plăci, în legătură/mănunchi/ciorchine"),
        ("XPZ", "Scânduri, în legătură/mănunchi/ciorchine"),
        ("XQA", "Tambur, oțel, cap nedemontabil"),
        ("XQB", "Tambur, oțel, cap detașabil"),
        ("XQC", "Tambur, aluminiu, cap nedemontabil"),
        ("XQD", "Tambur, aluminiu, cap detasabil"),
        ("XQF", "Tambur, plastic, cap nedemontabil"),
        ("XQG", "Tambur, plastic, cap detasabil"),
        ("XQH", "Butoi, lemn, tip bung"),
        ("XQJ", "Butoi, din lemn, cap detașabil"),
        ("XQK", "Jerican, oțel, cap nedemontabil"),
        ("XQL", "Jerican, oțel, cap detașabil"),
        ("XQM", "Bican, plastic, cap nedemontabil"),
        ("XQN", "Jerican, plastic, cap detașabil"),
        ("XQP", "Cutie, lemn, lemn natural, obisnuit"),
        ("XQQ", "Cutie, lemn, lemn natural, cu pereti rezistenti la cernere"),
        ("XQR", "Cutie, plastic, expandata"),
        ("XQS", "Cutie, plastic, solidă"),
        ("XRD", "Tijă"),
        ("XRG", "Inel"),
        ("XRJ", "Raft, cuier pentru haine"),
        ("XRK", "Raft"),
        ("XRL", "Tambur"),
        ("XRO", "Rolă"),
        ("XRT", "Rednet"),
        ("XRZ", "Tije, în legătură/mănunchi/ciorchine"),
        ("XSA", "Sac"),
        ("XSB", "Dală"),
        ("XSC", "Ladă, puțin adâncă"),
        ("XSD", "Ax"),
        ("XSE", "Cufăr de mare"),
        ("XSH", "plic"),
        ("XSI", "Derapaj"),
        ("XSK", "Carcasă, schelet"),
        ("XSL", "Slipsheet"),
        ("XSM", "Tablă"),
        ("XSO", "Bobină"),
        ("XSP", "Foaie, ambalaj din plastic"),
        ("XSS", "Carcasă, oțel"),
        ("XST", "Foaie"),
        ("XSU", "Valiză"),
        ("XSV", "Plic, oțel"),
        ("XSW", "Invelite în folie"),
        ("XSY", "Mânecă"),
        ("XSZ", "Foi, în legătură/bunchi/ciorchine"),
        ("XT1", "Tabletă"),
        ("XTB", "Cadă"),
        ("XTC", "Cutie de ceaiuri"),
        ("XTD", "Tub, pliabil"),
        ("XTE", "Anvelopă"),
        ("XTG", "Container cisternă, generic"),
        ("XTI", "Tierce"),
        ("XTK", "Rezervor, dreptunghiular"),
        ("XTL", "Cadă, cu capac"),
        ("XTN", "Bidon"),
        ("XTO", "Butoi mare"),
        ("XTR", "Cufăr"),
        ("XTS", "Legătură"),
        ("XTT", "Cutie, geantă"),
        ("XTU", "Tub"),
        ("XTV", "Tub, cu duza"),
        ("XTW", "Palet, triwall"),
        ("XTY", "Rezervor, cilindric"),
        ("XTZ", "Tuburi, în legătură/mănunchi/ciorchine"),
        ("XUC", "Neînchis"),
        ("XUN", "Unitate"),
        ("XVA", "TVA"),
        ("XVG", "Vrac, gaz (la 1031 mbar și 15°C)"),
        ("XVI", "Flacon"),
        ("XVK", "Vanpack"),
        ("XVL", "Vrac, lichid"),
        ("XVO", "Particule în vrac, solide, mari („noduli”)"),
        ("XVP", "Ambalat în vid"),
        ("XVQ", "Gaz lichefiat în vrac (la temperatură/presiune anormală)"),
        ("XVN", "Vehicul"),
        ("XVR", "Particule granulare în vrac, solide („granule”)"),
        ("XVS", "Vrac, fier vechi"),
        ("XVY", "Particule fine, solide, în vrac („pulberi”)"),
        ("XWA", "Container intermediar pentru vrac"),
        ("XWB", "Sticlă de răchită"),
        ("XWC", "Container intermediar pentru vrac, oțel"),
        ("XWD", "Container intermediar pentru vrac, aluminiu"),
        ("XWF", "Container intermediar pentru vrac, metalic"),
        ("XWG", "Container intermediar pentru vrac, oțel, presurizat > 10 kpa"),
        ("XWH", "Container intermediar pentru vrac, aluminiu, presurizat > 10 kpa"),
        ("XWJ", "Container intermediar pentru vrac, metal, presiune 10 kpa"),
        ("XWK", "Container intermediar pentru vrac, oțel, lichid"),
        ("XWL", "Container intermediar pentru vrac, aluminiu, lichid"),
        ("XWM", "Container intermediar pentru vrac, metal, lichid"),
        ("XWN", "Recipient intermediar pentru vrac, plastic țesut, fără strat/ căptușeală"),
        ("XWP", "Container intermediar pentru vrac, plastic țesut, acoperit"),
        ("XWQ", "Container intermediar pentru vrac, plastic țesut, cu căptușeală"),
        ("XWR", "Container intermediar pentru vrac, plastic țesut, acoperit și căptușeală"),
        ("XWS", "Recipient intermediar pentru vrac, folie de plastic"),
        ("XWT", "Container intermediar pentru vrac, textil cu strat/ căptușeală"),
        ("XWU", "Recipient intermediar pentru vrac, lemn natural, cu căptușeală interioară"),
        ("XWV", "Container intermediar pentru vrac, textil, acoperit"),
        ("XWW", "Container intermediar pentru vrac, textil, cu căptușeală"),
        ("XWX", "Container intermediar pentru vrac, textil, acoperit și căptușeală"),
        ("XWY", "Container intermediar pentru vrac, placaj, cu căptușeală interioară"),
        ("XWZ", "Container intermediar pentru vrac, lemn reconstituit, cu căptușeală interioară"),
        ("XXA", "Geantă, plastic țesut, fără strat/ căptușeală interioară"),
        ("XXB", "Geantă, plastic țesut, rezistentă la cernere"),
        ("XXC", "Geanta, țesut din plastic, rezistentă la apă"),
        ("XXD", "Geanta, folie de plastic"),
        ("XXF", "Geantă, textil, fără strat/ căptușeală interioară"),
        ("XXG", "Geanta, material textil, rezistent la cernere"),
        ("XXH", "Geanta, textil, rezistenta la apa"),
        ("XXJ", "Geantă, hârtie, multi-pereți"),
        ("XXK", "Geanta, hartie, multi-perete, rezistenta la apa"),
        ("XYA", "Ambalaj compozit, recipient din plastic în tambur de oțel"),
        ("XYB", "Ambalaj compozit, recipient din plastic în cutie de oțel"),
        ("XYC", "Ambalaj compozit, recipient din plastic în tambur de aluminiu"),
        ("XYD", "Ambalaj compozit, recipient din plastic în ladă de aluminiu"),
        ("XYF", "Ambalaj compozit, recipient din plastic în cutie de lemn"),
        ("XYG", "Ambalaj compozit, recipient din plastic în tambur de placaj"),
        ("XYH", "Ambalaj compozit, recipient din plastic în cutie de placaj"),
        ("XYJ", "Ambalaj compozit, recipient din plastic în tambur din fibre"),
        ("XYK", "Ambalaj compozit, recipient din plastic în cutie din carton"),
        ("XYL", "Ambalaj compozit, recipient din plastic în tambur de plastic"),
        ("XYM", "Ambalaj compozit, recipient din plastic în cutie solidă din plastic"),
        ("XYN", "Ambalaj compozit, recipient din sticlă în tambur de oțel"),
        ("XYP", "Ambalaj compozit, recipient de sticlă în cutie de oțel"),
        ("XYQ", "Ambalaj compozit, recipient din sticlă în tambur de aluminiu"),
        ("XYR", "Ambalaj compozit, recipient din sticlă în ladă de aluminiu"),
        ("XYS", "Ambalaj compozit, recipient de sticlă în cutie de lemn"),
        ("XYT", "Ambalaj compozit, recipient de sticlă în tambur de placaj"),
        ("XYV", "Ambalaj compozit, recipient din sticlă în coș din răchită"),
        ("XYW", "Ambalaj compozit, recipient din sticlă în tambur din fibre"),
        ("XYX", "Ambalaj compozit, recipient de sticlă în cutie din carton"),
        ("XYY", "Ambalaj compozit, recipient din sticlă în ambalaj din plastic extensibil"),
        ("XYZ", "Ambalaj compozit, recipient din sticlă în ambalaj solid din plastic"),
        ("XZA", "Container intermediar pentru vrac, hârtie, multi-pereți"),
        ("XZB", "Geanta, mare"),
        ("XZC", "Container intermediar pentru vrac, hârtie, multi-pereți, rezistent la apă"),
        ("XZD", "Container intermediar pentru vrac, plastic rigid, cu echipament structural, solide"),
        ("XZF", "Container intermediar pentru vrac, plastic rigid, autoportant, solide"),
        ("XZG", "Container intermediar pentru vrac, plastic rigid, cu echipament structural, presurizat"),
        ("XZH", "Container intermediar pentru vrac, plastic rigid, de sine stătător, sub presiune"),
        ("XZJ", "Container intermediar pentru vrac, plastic rigid, cu echipament structural, lichide"),
        ("XZK", "Container intermediar pentru vrac, plastic rigid, de sine statator, lichide"),
        ("XZL", "Container intermediar pentru vrac, compozit, plastic rigid, solide"),
        ("XZM", "Container intermediar pentru vrac, compozit, plastic flexibil, solide"),
        ("XZN", "Container intermediar pentru vrac, compozit, plastic rigid, sub presiune"),
        ("XZP", "Container intermediar pentru vrac, compozit, plastic flexibil, sub presiune"),
        ("XZQ", "Container intermediar pentru vrac, compozit, plastic rigid, lichide"),
        ("XZR", "Container intermediar pentru vrac, compozit, plastic flexibil, lichide"),
        ("XZS", "Container intermediar pentru vrac, compozit"),
        ("XZT", "Container intermediar pentru vrac, plăci de fibre"),
        ("XZU", "Container intermediar pentru vrac, flexibil"),
        ("XZV", "Container intermediar pentru vrac, din metal, altul decât oțel"),
        ("XZW", "Container intermediar pentru vrac, lemn natural"),
        ("XZX", "Container intermediar pentru vrac, placaj"),
        ("XZY", "Container intermediar pentru vrac, lemn reconstituit"),
        ("XZZ", "Definite reciproc"),
        ("XLTR", "Vrac, litru de produse petroliere lichide (la 1031 mbar și 15°C)"),
        ("DBM", "Decibel-miliwați"),
        ("DBW", "Decibel Watt"),
        ("FNU", "Unitate nefelometrică de formazină"),
        ("HAD", "Bucată zi"),
        ("HMO", "Bucată lună"),
        ("HWE", "Bucată săptămână"),
        ("KWY", "kilowați an"),
        ("MKD", "Zi metru pătrat"),
        ("MKM", "Lună metru pătrat"),
        ("MKW", "Săptămâna metru pătrat"),
        ("MNJ", "Mega Joule pe metru cub normalizat"),
        ("MQD", "Zi metru cub"),
        ("MQM", "Luna metru cub"),
        ("MQW", "Săptămâna metru cub"),
        ("MRD", "Zi metru"),
        ("MRM", "Lună metru"),
        ("MRW", "Săptămână metru"),
        ("MTZ", "milihertz"),
        ("NTU", "Unitatea de turbiditate nefelometrică"),
        ("Z9", "nanomol"),
        ("XO1", "Cușcă pe două fețe pe roți cu curea de fixare"),
        ("XO2", "Cărucior"),
        ("XO3", "Palet unic ISO 0 - 1/2 EURO Palet"),
        ("XO4", "Palet unic ISO 1 - 1/1 EURO Palet"),
        ("XO5", "Palet unic ISO 2 - 2/1 EURO Palet"),
        ("XO6", "Palet cu dimensiuni exceptionale"),
        ("XO7", "Palet din lemn 40 cm x 80 cm"),
        ("XO8", "Palet plastic SRS 60 cm x 80 cm"),
        ("XO9", "Palet plastic SRS 80 cm x 120 cm"),
        ("XOG", "Palet ISO 0 - 1/2 EURO Palet"),
        ("XOH", "Palet ISO 1 - 1/1 EURO Palet"),
        ("XOI", "Palet ISO 2 – 2/1 EURO Palet"),
        ("XOJ", "Palet 1/4 EURO"),
        ("XOL", "Palet 1/8 EURO"),
        ("XOM", "Palet sintetic ISO 1"),
        ("XON", "Palet sintetic ISO 2"),
        ("XOP", "Palet angro"),
        ("XOQ", "Palet 80 X 100 cm"),
        ("XOR", "Palet 60 X 100 cm"),
        ("XOS", "Palet unic"),
        ("XOV", "Palet returnabil"),
        ("XOW", "Geanta mare, dimensiunea paletului"),
        ("XOX", "Un palet pe roți cu margine ridicată (81 x 67 x 135)"),
        ("XOY", "Palet pe roți cu margine ridicată (81 x 72 x 135)"),
        ("XOZ", "Palet cu roți cu jantă ridicată ( 81 x 60 x 16)"),
        ("XP1", "Palet CHEP 60 cm x 80 cm"),
        ("XP3", "Palet LPR 60 cm x 80 cm"),
        ("XP4", "Palet LPR 80 cm x 120 cm"),
        ("XSX", "Set"),
    ];
}
