object frmIstoricNota: TfrmIstoricNota
  Left = 143
  Top = 0
  Caption = 'Istoric Nota'
  ClientHeight = 667
  ClientWidth = 1109
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  DesignSize = (
    1109
    667)
  PixelsPerInch = 96
  TextHeight = 13
  object Button1: TButton
    Left = 1020
    Top = 635
    Width = 75
    Height = 25
    Anchors = [akRight, akBottom]
    Caption = 'OK'
    TabOrder = 0
    OnClick = Button1Click
  end
  object TreeIstoricNota: TcxDBTreeList
    Left = 0
    Top = 0
    Width = 1109
    Height = 633
    Align = alTop
    Bands = <
      item
        Caption.AlignHorz = taCenter
      end>
    DataController.DataSource = DataSource1
    DataController.ParentField = 'istoric_nr'
    DataController.KeyField = 'NR'
    DefaultLayout = True
    LookAndFeel.Kind = lfOffice11
    LookAndFeel.NativeStyle = False
    Navigator.Buttons.CustomButtons = <>
    OptionsBehavior.GoToNextCellOnTab = True
    OptionsBehavior.AutoDragCopy = True
    OptionsBehavior.DragCollapse = False
    OptionsBehavior.ExpandOnIncSearch = True
    OptionsBehavior.ShowHourGlass = False
    OptionsCustomizing.BandCustomizing = False
    OptionsCustomizing.BandVertSizing = False
    OptionsCustomizing.ColumnsQuickCustomization = True
    OptionsCustomizing.ColumnVertSizing = False
    OptionsData.Editing = False
    OptionsData.AnsiSort = True
    OptionsData.Deleting = False
    OptionsSelection.CellSelect = False
    OptionsSelection.HideFocusRect = False
    OptionsSelection.InvertSelect = False
    OptionsView.CellTextMaxLineCount = -1
    OptionsView.ShowEditButtons = ecsbFocused
    OptionsView.BandLineHeight = 19
    OptionsView.ColumnAutoWidth = True
    ParentColor = False
    Preview.AutoHeight = False
    Preview.MaxLineCount = 2
    RootValue = -1
    ScrollbarAnnotations.CustomAnnotations = <>
    TabOrder = 1
    object TreeIstoricNotaNR: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'NR'
      Width = 100
      Position.ColIndex = 28
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCOD: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'COD'
      Width = 100
      Position.ColIndex = 29
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaPOZ: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'POZ'
      Width = 100
      Position.ColIndex = 30
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaJURNAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Jurnal'
      DataBinding.FieldName = 'JURNAL'
      Width = 100
      Position.ColIndex = 0
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaNRDOC: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Numar'
      DataBinding.FieldName = 'NRDOC'
      Width = 100
      Position.ColIndex = 1
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaDATA: TcxDBTreeListColumn
      PropertiesClassName = 'TcxDateEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.DateButtons = [btnClear, btnToday]
      Properties.DateOnError = deToday
      Properties.InputKind = ikRegExpr
      Caption.Text = 'Data'
      DataBinding.FieldName = 'DATA'
      Width = 100
      Position.ColIndex = 2
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaEXPLICATIE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxTextEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Explicatie'
      DataBinding.FieldName = 'EXPLICATIE'
      Width = 100
      Position.ColIndex = 3
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaVALOARE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxCurrencyEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.AssignedValues.MaxValue = True
      Properties.AssignedValues.MinValue = True
      Properties.DecimalPlaces = 2
      Properties.DisplayFormat = ',0.00;-,0.00'
      Properties.Nullable = False
      Properties.ReadOnly = True
      Caption.Text = 'Valoare'
      DataBinding.FieldName = 'VALOARE'
      Width = 100
      Position.ColIndex = 4
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCONT_DEBT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Cont debit'
      DataBinding.FieldName = 'CONT_DEBT'
      Width = 100
      Position.ColIndex = 5
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaREPARTITOR_DEBIT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Rep. debit'
      DataBinding.FieldName = 'REPARTITOR_DEBIT'
      Width = 100
      Position.ColIndex = 6
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaAC: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'AC'
      Width = 100
      Position.ColIndex = 37
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaECL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ECL'
      Width = 100
      Position.ColIndex = 43
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaC_O: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'C_O'
      Width = 100
      Position.ColIndex = 42
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaBUGET: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'BUGET'
      Width = 100
      Position.ColIndex = 41
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCOMPUSA: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'COMPUSA'
      Width = 100
      Position.ColIndex = 40
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCONTD: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'CONTD'
      Width = 100
      Position.ColIndex = 39
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCONTC: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'CONTC'
      Width = 100
      Position.ColIndex = 38
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCONT_CRED: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Cont credit'
      DataBinding.FieldName = 'CONT_CRED'
      Width = 100
      Position.ColIndex = 7
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_INITIAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_INITIAL'
      Width = 100
      Position.ColIndex = 36
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_PARINTE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_PARINTE'
      Width = 100
      Position.ColIndex = 35
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaDATA_OPERARE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxDateEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.DateButtons = [btnClear, btnToday]
      Properties.DateOnError = deToday
      Properties.InputKind = ikRegExpr
      Visible = False
      DataBinding.FieldName = 'DATA_OPERARE'
      Width = 100
      Position.ColIndex = 34
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCODREP_OLD: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'CODREP_OLD'
      Width = 100
      Position.ColIndex = 33
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaSTARE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'STARE'
      Width = 100
      Position.ColIndex = 32
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_ANGAJAMENTE_DEFALCARE: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_ANGAJAMENTE_DEFALCARE'
      Width = 100
      Position.ColIndex = 31
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaREPARTITOR_CREDIT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Repartitor credit'
      DataBinding.FieldName = 'REPARTITOR_CREDIT'
      Width = 100
      Position.ColIndex = 8
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaMODUL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Modul'
      DataBinding.FieldName = 'MODUL'
      Width = 100
      Position.ColIndex = 9
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCOD_ECONOMIC: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Clasa economica'
      DataBinding.FieldName = 'COD_ECONOMIC'
      Width = 100
      Position.ColIndex = 10
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCOD_FUNCTIONAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Caption.Text = 'Clasa functionala'
      DataBinding.FieldName = 'COD_FUNCTIONAL'
      Width = 100
      Position.ColIndex = 27
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaNR_OP: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'NR_OP'
      Width = 100
      Position.ColIndex = 26
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_ORDIN_PLATA: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_ORDIN_PLATA'
      Width = 100
      Position.ColIndex = 25
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaCODGEST_OLD: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'CODGEST_OLD'
      Width = 100
      Position.ColIndex = 24
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaOLD_CONT_C: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'OLD_CONT_C'
      Width = 100
      Position.ColIndex = 23
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaOLD_CONT_D: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'OLD_CONT_D'
      Width = 100
      Position.ColIndex = 22
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaTRANSFERAT_C: TcxDBTreeListColumn
      PropertiesClassName = 'TcxCheckBoxProperties'
      Properties.Alignment = taLeftJustify
      Properties.NullStyle = nssUnchecked
      Properties.ReadOnly = True
      Properties.ValueChecked = 'True'
      Properties.ValueGrayed = ''
      Properties.ValueUnchecked = 'False'
      Visible = False
      DataBinding.FieldName = 'TRANSFERAT_C'
      Width = 100
      Position.ColIndex = 21
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaTRANSFERAT_D: TcxDBTreeListColumn
      PropertiesClassName = 'TcxCheckBoxProperties'
      Properties.Alignment = taLeftJustify
      Properties.NullStyle = nssUnchecked
      Properties.ReadOnly = True
      Properties.ValueChecked = 'True'
      Properties.ValueGrayed = ''
      Properties.ValueUnchecked = 'False'
      Visible = False
      DataBinding.FieldName = 'TRANSFERAT_D'
      Width = 100
      Position.ColIndex = 20
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_UNIC_MODUL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_UNIC_MODUL'
      Width = 100
      Position.ColIndex = 19
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_DOCUMENT_MODUL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_DOCUMENT_MODUL'
      Width = 100
      Position.ColIndex = 18
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaID_MATERIAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ID_MATERIAL'
      Width = 100
      Position.ColIndex = 17
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaTIP_DOCUMENT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'TIP_DOCUMENT'
      Width = 100
      Position.ColIndex = 16
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaNUMAR_DOCUMENT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'NUMAR_DOCUMENT'
      Width = 100
      Position.ColIndex = 15
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaDATA_DOCUMENT: TcxDBTreeListColumn
      PropertiesClassName = 'TcxDateEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.DateButtons = [btnClear, btnToday]
      Properties.DateOnError = deToday
      Properties.InputKind = ikRegExpr
      Visible = False
      DataBinding.FieldName = 'DATA_DOCUMENT'
      Width = 100
      Position.ColIndex = 14
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaNUME_MATERIAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'NUME_MATERIAL'
      Width = 100
      Position.ColIndex = 13
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaANALITIC_MATERIAL: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'ANALITIC_MATERIAL'
      Width = 100
      Position.ColIndex = 12
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
    object TreeIstoricNotaistoric_nr: TcxDBTreeListColumn
      PropertiesClassName = 'TcxMaskEditProperties'
      Properties.Alignment.Horz = taLeftJustify
      Properties.MaxLength = 0
      Properties.ReadOnly = True
      Visible = False
      DataBinding.FieldName = 'istoric_nr'
      Width = 100
      Position.ColIndex = 11
      Position.RowIndex = 0
      Position.BandIndex = 0
      Summary.FooterSummaryItems = <>
      Summary.GroupFooterSummaryItems = <>
    end
  end
  object qryNota: TZQuery
    Connection = frmData.dbContabilitate
    SQL.Strings = (
      'select * from cnote where nr > 27774930')
    Params = <>
    Left = 64
    Top = 40
  end
  object DataSource1: TDataSource
    DataSet = qryNota
    Left = 64
    Top = 72
  end
end
