<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <Deterministic>false</Deterministic>
    <AssemblyVersion>1.0.*</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <Configurations>Debug;Release;EasyTest</Configurations>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="DevExpress.Drawing.Skia" />
    <PackageReference Include="DevExpress.ExpressApp.Api.EFCore.All" />
    <PackageReference Include="DevExpress.ExpressApp.CodeAnalysis" />
    <PackageReference Include="DevExpress.ExpressApp.ReportsV2" />
    <PackageReference Include="DevExpress.ExpressApp.Validation" />
    <PackageReference Include="Microsoft.CodeAnalysis.Workspaces.MSBuild">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Atlas.Conta.BackOffice.Module\Atlas.Conta.BackOffice.Module.csproj" />
  </ItemGroup>
</Project>
