unit UpdStructure;

interface

{actualizeaza structura pt casa}
procedure DoUpdateStructure;

implementation

uses
  ZeosDBUtile;

procedure DoUpdateStructure;
begin
  DBExecSQL(
    'IF NOT EXISTS(SELECT TOP 1 1 FROM SYSCOLUMNS WHERE NAME LIKE ''IS_TEMPOR'' AND ID= OBJECT_ID(''CASIERIE''))'#13#10+
    ' ALTER TABLE CASIERIE ADD IS_TEMPOR BIT'#13#10+
    'IF NOT EXISTS(SELECT TOP 1 1 FROM SYSCOLUMNS WHERE NAME LIKE ''OLD_ID'' AND ID= OBJECT_ID(''SHARE_POINT''))'#13#10+
    ' ALTER TABLE SHARE_POINT ADD OLD_ID INT'#13#10+
    'IF NOT EXISTS(SELECT TOP 1 1 FROM SYSCOLUMNS WHERE NAME LIKE ''NR_EXTRAS'' AND ID = OBJECT_ID(''BREGISTRU''))'#13#10+
    ' ALTER TABLE BREGISTRU ADD NR_EXTRAS VARCHAR(50)'#13#10+
    'IF NOT EXISTS(SELECT TOP 1 1 FROM SYSCOLUMNS WHERE NAME LIKE ''DATA_EXTRAS'' AND ID = OBJECT_ID(''BREGISTRU''))'#13#10+
    ' ALTER TABLE BREGISTRU ADD DATA_EXTRAS DATETIME'#13#10+
    'if exists(select top 1 1 from sysobjects where name like ''spUpdStructura'')'#13#10+
    ' exec spUpdStructura'#13#10+
    'IF EXISTS(SELECT TOP 1 1 FROM SYSOBJECTS WHERE NAME LIKE ''SP_UPD_STR_CASIERIE'')'#13#10+
    ' EXEC SP_UPD_STR_CASIERIE'#13#10+
    'IF EXISTS(SELECT TOP 1 1 FROM SYSOBJECTS WHERE NAME LIKE ''SP_UPD_ARH_BREGISTRU'')'#13#10+
    ' EXEC SP_UPD_ARH_BREGISTRU'#13#10
  );
end;


end.
