; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Contabilitate
AppVerName=Contabilitate ver.1.0
AppPublisher=Advanced Technology Systems
AppPublisherURL=http://ats.com.ro
AppSupportURL=http://ats.com.ro
AppUpdatesURL=http://ats.com.ro
DefaultDirName={pf}\Contabilitate
DefaultGroupName=Contabilitate
OutputDir=S:\Develop\SQL\Develop\ContaD7\Kit
OutputBaseFilename=setup
Compression=lzma
SolidCompression=true
PrivilegesRequired=admin
ShowLanguageDialog=yes

[Languages]
Name: english; MessagesFile: compiler:Default.isl

[Tasks]
Name: desktopicon; Description: {cm:CreateDesktopIcon}; GroupDescription: {cm:AdditionalIcons}; Flags: unchecked

[Files]
Source: S:\Develop\SQL\Develop\ContaD7\EXE\Contabilitate.exe; DestDir: {app}; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: D:\Temp\salary.exe; DestDir: {app}; Flags: ignoreversion; Tasks: ; Languages: 

[Icons]
Name: {group}\Contabilitate; Filename: {app}\Contabilitate.exe; IconIndex: 0; WorkingDir: {app}
Name: {userdesktop}\Contabilitate; Filename: {app}\Contabilitate.exe; Tasks: desktopicon; WorkingDir: {app}; IconIndex: 0
Name: {group}\Salary; Filename: {app}\salary.exe; WorkingDir: {app}; IconFilename: {app}\salary.exe; IconIndex: 0; Tasks: ; Languages: 

[Run]
Filename: {app}\Contabilitate.exe; Description: {cm:LaunchProgram,Contabilitate}; Flags: nowait postinstall skipifsilent

[Registry]
Root: HKLM; SubKey: SOFTWARE\ATS\Contabilitate\Connects; ValueType: string; ValueName: TARGOVISTE; ValueData: Contabilitate
Root: HKLM; SubKey: SOFTWARE\ATS\Contabilitate\Servers\TARGOVISTE; ValueType: string; ValueName: DataBase; ValueData: Contabilitate
Root: HKLM; SubKey: SOFTWARE\ATS\Contabilitate\Servers\TARGOVISTE; ValueType: string; ValueName: Server; ValueData: CERBER
Root: HKLM; SubKey: SOFTWARE\Microsoft\MSSQLServer\Client\ConnectTo; ValueType: string; ValueName: CERBER; ValueData: DBMSSOCN,192.168.0.2,1433
Root: HKLM; Subkey: SOFTWARE\ATS\Salarii v2\Connects; ValueType: string; ValueName: TARGOVISTE; ValueData: Salarizare
Root: HKLM; Subkey: SOFTWARE\ATS\Salarii v2\Servers\TARGOVISTE; ValueType: string; ValueName: DataBase; ValueData: SALARII
Root: HKLM; Subkey: SOFTWARE\ATS\Salarii v2\Servers\TARGOVISTE; ValueType: string; ValueName: SERVER; ValueData: CERBER
